import { SeedTag } from '@/genesis/schemas/atoms';
import slugify from 'lodash/kebabCase';

const RAW_TAGS = [
  // --- Terrains / Biomes ---
  { name: 'Arctic', category: 'thematic', color: '#A5F2F3' },
  { name: 'Coastal', category: 'thematic', color: '#4ECDC4' },
  { name: 'Desert', category: 'thematic', color: '#FFE66D' },
  { name: 'Forest', category: 'thematic', color: '#556B2F' },
  { name: 'Grassland', category: 'thematic', color: '#9ACD32' },
  { name: 'Hill', category: 'thematic', color: '#808000' },
  { name: 'Mountain', category: 'thematic', color: '#8B4513' },
  { name: 'Swamp', category: 'thematic', color: '#2E8B57' },
  { name: 'Underdark', category: 'thematic', color: '#800080' },
  { name: 'Underwater', category: 'thematic', color: '#000080' },
  { name: 'Urban', category: 'thematic', color: '#778899' },

  // --- Magic Schools ---
  { name: 'Abjuration', category: 'mechanic', color: '#6495ED' },
  { name: 'Conjuration', category: 'mechanic', color: '#FFD700' },
  { name: 'Divination', category: 'mechanic', color: '#C0C0C0' },
  { name: 'Enchantment', category: 'mechanic', color: '#FF69B4' },
  { name: 'Evocation', category: 'mechanic', color: '#FF4500' },
  { name: 'Illusion', category: 'mechanic', color: '#9370DB' },
  { name: 'Necromancy', category: 'mechanic', color: '#2F4F4F' },
  { name: 'Transmutation', category: 'mechanic', color: '#32CD32' },

  // --- Languages ---
  { name: 'Common', category: 'general', color: '#D3D3D3' },
  { name: 'Dwarvish', category: 'general', color: '#A9A9A9' },
  { name: 'Elvish', category: 'general', color: '#90EE90' },
  { name: 'Giant', category: 'general', color: '#8B0000' },
  { name: 'Gnomish', category: 'general', color: '#DEB887' },
  { name: 'Goblin', category: 'general', color: '#556B2F' },
  { name: 'Halfling', category: 'general', color: '#F0E68C' },
  { name: 'Orc', category: 'general', color: '#696969' },
  { name: 'Abyssal', category: 'general', color: '#800000' },
  { name: 'Celestial', category: 'general', color: '#FFFFFF' },
  { name: 'Draconic', category: 'general', color: '#B8860B' },
  { name: 'Deep Speech', category: 'general', color: '#4B0082' },
  { name: 'Infernal', category: 'general', color: '#8B0000' },
  { name: 'Primordial', category: 'general', color: '#008B8B' },
  { name: 'Sylvan', category: 'general', color: '#228B22' },
  { name: 'Undercommon', category: 'general', color: '#483D8B' },

  // --- Damage Types ---
  { name: 'Acid', category: 'mechanic', color: '#7FFF00' },
  { name: 'Bludgeoning', category: 'mechanic', color: '#808080' },
  { name: 'Cold', category: 'mechanic', color: '#00FFFF' },
  { name: 'Fire', category: 'mechanic', color: '#FF0000' },
  { name: 'Force', category: 'mechanic', color: '#FFFFFF' },
  { name: 'Lightning', category: 'mechanic', color: '#FFFF00' },
  { name: 'Necrotic', category: 'mechanic', color: '#000000' },
  { name: 'Piercing', category: 'mechanic', color: '#A9A9A9' },
  { name: 'Poison', category: 'mechanic', color: '#00FF7F' },
  { name: 'Psychic', category: 'mechanic', color: '#FF1493' },
  { name: 'Radiant', category: 'mechanic', color: '#FFD700' },
  { name: 'Slashing', category: 'mechanic', color: '#C0C0C0' },
  { name: 'Thunder', category: 'mechanic', color: '#1E90FF' },

  // --- Conditions ---
  { name: 'Blinded', category: 'mechanic', color: '#696969' },
  { name: 'Charmed', category: 'mechanic', color: '#FF69B4' },
  { name: 'Deafened', category: 'mechanic', color: '#A9A9A9' },
  { name: 'Exhaustion', category: 'mechanic', color: '#8B4513' },
  { name: 'Frightened', category: 'mechanic', color: '#4B0082' },
  { name: 'Grappled', category: 'mechanic', color: '#800000' },
  { name: 'Incapacitated', category: 'mechanic', color: '#808080' },
  { name: 'Invisible', category: 'mechanic', color: '#F0F8FF' },
  { name: 'Paralyzed', category: 'mechanic', color: '#FFFF00' },
  { name: 'Petrified', category: 'mechanic', color: '#708090' },
  { name: 'Poisoned', category: 'mechanic', color: '#00FF7F' },
  { name: 'Prone', category: 'mechanic', color: '#D2691E' },
  { name: 'Restrained', category: 'mechanic', color: '#8B0000' },
  { name: 'Stunned', category: 'mechanic', color: '#FFFFE0' },
  { name: 'Unconscious', category: 'mechanic', color: '#000000' },

  // --- Sizes ---
  { name: 'Tiny', category: 'mechanic', color: '#E0FFFF' },
  { name: 'Small', category: 'mechanic', color: '#ADD8E6' },
  { name: 'Medium', category: 'mechanic', color: '#87CEEB' },
  { name: 'Large', category: 'mechanic', color: '#4682B4' },
  { name: 'Huge', category: 'mechanic', color: '#000080' },
  { name: 'Gargantuan', category: 'mechanic', color: '#191970' },

  // --- Alignments ---
  { name: 'Lawful Good', category: 'meta', color: '#FFFACD' },
  { name: 'Neutral Good', category: 'meta', color: '#F0FFF0' },
  { name: 'Chaotic Good', category: 'meta', color: '#F5FFFA' },
  { name: 'Lawful Neutral', category: 'meta', color: '#D3D3D3' },
  { name: 'Neutral', category: 'meta', color: '#A9A9A9' },
  { name: 'Chaotic Neutral', category: 'meta', color: '#808080' },
  { name: 'Lawful Evil', category: 'meta', color: '#B22222' },
  { name: 'Neutral Evil', category: 'meta', color: '#800000' },
  { name: 'Chaotic Evil', category: 'meta', color: '#FF0000' },
  { name: 'Unaligned', category: 'meta', color: '#778899' },

  // --- Rarities ---
  { name: 'Common', category: 'meta', color: '#D3D3D3' },
  { name: 'Uncommon', category: 'meta', color: '#32CD32' },
  { name: 'Rare', category: 'meta', color: '#00BFFF' },
  { name: 'Very Rare', category: 'meta', color: '#9400D3' },
  { name: 'Legendary', category: 'meta', color: '#FFD700' },
  { name: 'Artifact', category: 'meta', color: '#FF4500' },

  // --- Skills ---
  { name: 'Athletics', category: 'mechanic', color: '#CD5C5C' },
  { name: 'Acrobatics', category: 'mechanic', color: '#FFA07A' },
  { name: 'Sleight of Hand', category: 'mechanic', color: '#ffa500' },
  { name: 'Stealth', category: 'mechanic', color: '#2F4F4F' },
  { name: 'Arcana', category: 'mechanic', color: '#8A2BE2' },
  { name: 'History', category: 'mechanic', color: '#8B4513' },
  { name: 'Investigation', category: 'mechanic', color: '#4682B4' },
  { name: 'Nature', category: 'mechanic', color: '#228B22' },
  { name: 'Religion', category: 'mechanic', color: '#FFD700' },
  { name: 'Animal Handling', category: 'mechanic', color: '#F4A460' },
  { name: 'Insight', category: 'mechanic', color: '#9370DB' },
  { name: 'Medicine', category: 'mechanic', color: '#00CED1' },
  { name: 'Perception', category: 'mechanic', color: '#FF8C00' },
  { name: 'Survival', category: 'mechanic', color: '#556B2F' },
  { name: 'Deception', category: 'mechanic', color: '#800080' },
  { name: 'Intimidation', category: 'mechanic', color: '#8B0000' },
  { name: 'Performance', category: 'mechanic', color: '#FF69B4' },
  { name: 'Persuasion', category: 'mechanic', color: '#1E90FF' },

  // --- Misc Mechanics ---
  { name: 'Weapon', category: 'mechanic', color: '#A52A2A' },
  { name: 'Armor', category: 'mechanic', color: '#708090' },
  { name: 'Potion', category: 'mechanic', color: '#FF69B4' },
  { name: 'Scroll', category: 'mechanic', color: '#F0E68C' },
  { name: 'Wondrous Item', category: 'mechanic', color: '#9370DB' },
  { name: 'Ring', category: 'mechanic', color: '#FFD700' },
  { name: 'Rod', category: 'mechanic', color: '#8B4513' },
  { name: 'Staff', category: 'mechanic', color: '#8B4513' },
  { name: 'Wand', category: 'mechanic', color: '#D2691E' },
  { name: 'Tool', category: 'mechanic', color: '#808080' },

  // --- Monster Types ---
  { name: 'Aberration', category: 'mechanic', color: '#800080' },
  { name: 'Beast', category: 'mechanic', color: '#8B4513' },
  { name: 'Celestial', category: 'mechanic', color: '#FFFF00' },
  { name: 'Construct', category: 'mechanic', color: '#808080' },
  { name: 'Dragon', category: 'mechanic', color: '#B22222' },
  { name: 'Elemental', category: 'mechanic', color: '#FF4500' },
  { name: 'Fey', category: 'mechanic', color: '#FF69B4' },
  { name: 'Fiend', category: 'mechanic', color: '#8B0000' },
  { name: 'Giant', category: 'mechanic', color: '#A9A9A9' },
  { name: 'Humanoid', category: 'mechanic', color: '#D2B48C' },
  { name: 'Monstrosity', category: 'mechanic', color: '#2F4F4F' },
  { name: 'Ooze', category: 'mechanic', color: '#00FF00' },
  { name: 'Plant', category: 'mechanic', color: '#008000' },
  { name: 'Undead', category: 'mechanic', color: '#4B0082' },
] as const;

export const TAGS: SeedTag[] = RAW_TAGS.map((t) => ({
  name: t.name,
  slug: slugify(t.name),
  color: t.color,
  category: t.category,
}));
