import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'acolyte',
  name: 'Acolyte',
  description:
    '### Special Abilities\n["Spellcasting: The acolyte is a 1st-level spellcaster. Its spellcasting ability is Wisdom (spell save DC 12, +4 to hit with spell attacks). The acolyte has following cleric spells prepared: Cantrips (at will): light, sacred flame, thaumaturgy; 1st level (3 slots): bless, cure wounds, sanctuary"]\n\n### Actions\n["Club: Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage."]',
  size: 'Medium',
  type: 'humanoid',
  alignment: 'any alignment',
  level: 1,
  ac: 10,
  hp: 9,
  hit_dice: '2d8',
  challenge_rating: 0.25,
  xp: 50,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 12,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  inventory: [
    {
      item: 'club',
      quantity: 1,
      slot: 'main_hand',
      isEquipped: true,
    },
  ],
  actions: [
    'acolyte-bless',
    'acolyte-cure-wounds',
    'acolyte-light',
    'acolyte-sacred-flame',
    'acolyte-sanctuary',
    'acolyte-thaumaturgy',
  ],
});
