import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'basilisk',
  name: 'Basilisk',
  description:
    '### Special Abilities\n[{"name":"Petrifying Gaze","desc":"If a creature starts its turn within 30 ft. of the basilisk and the two of them can see each other, the basilisk can force the creature to make a DC 12 Constitution saving throw if the basilisk isn\'t incapacitated. On a failed save, the creature magically begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or other magic. A creature that isn\'t surprised can avert its eyes to avoid the saving throw at the start of its turn. If it does so, it can\'t see the basilisk until the start of its next turn, when it can avert its eyes again. If it looks at the basilisk in the meantime, it must immediately make the save. If the basilisk sees its reflection within 30 ft. of it in bright light, it mistakes itself for a rival and targets itself with its gaze."}]\n\n### Actions\n[{"name":"Bite","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage plus 7 (2d6) poison damage.","attack_bonus":5,"damage":[{"damage_type":"piercing","damage_dice":"2d6+3"},{"damage_type":"poison","damage_dice":"2d6"}]}]',
  size: 'Medium',
  type: 'monstrosity',
  alignment: 'unaligned',
  level: 3,
  ac: 12,
  hp: 52,
  hit_dice: '8d8',
  challenge_rating: 3,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 20,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 0,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: ['basilisk-bite', 'basilisk-petrifying-gaze'],
});
