import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'chain-devil',
  name: 'Chain Devil',
  description:
    '### Special Abilities\n[{"name":"Devil\'s Sight","desc":"Magical darkness doesn\'t impede the devil\'s darkvision."},{"name":"Magic Resistance","desc":"The devil has advantage on saving throws against spells and other magical effects."}]\n\n### Actions\n[{"name":"Multiattack","desc":"The devil makes two attacks with its chains."},{"name":"Chain","desc":"Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 11 (2d6 + 4) slashing damage. The target is grappled (escape DC 14) if the devil isn\'t already grappling a creature. Until this grapple ends, the target is restrained and takes 7 (2d6) piercing damage at the start of each of its turns."},{"name":"Animate Chains","desc":"Up to four chains the devil can see within 60 feet of it magically sprout razor-edged barbs and animate under the devil\'s control, provided that the chains aren\'t being worn or carried. Each animated chain is an object with AC 20, 20 hit points, resistance to piercing damage, and immunity to psychic and thunder damage. When the devil uses Multiattack on its turn, it can use each animated chain to make one additional chain attack. An animated chain can grapple one creature of its own but can\'t make attacks while grappling. An animated chain reverts to its inanimate state if reduced to 0 hit points or if the devil is incapacitated or dies."}]',
  size: 'Medium',
  type: 'fiend',
  alignment: 'lawful evil',
  level: 8,
  ac: 16,
  hp: 85,
  hit_dice: '10d8+40',
  challenge_rating: 8,
  xp: 3900,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: ['con', 'wis', 'cha'],
    skills: [],
    passivePerception: 11,
    darkvision: 120,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: [
    'chain-devil-animate-chains',
    'chain-devil-chain',
    'chain-devil-devil-s-sight',
    'chain-devil-magic-resistance',
    'chain-devil-multiattack',
  ],
});
