import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'cloud-giant',
  name: 'Cloud Giant',
  description:
    '### Special Abilities\n[{"name": "Keen Smell", "description": "The giant has advantage on Wisdom (Perception) checks that rely on smell."}, {"name": "Innate Spellcasting", "description": "The giant\'s innate spellcasting ability is Charisma. It can innately cast the following spells, requiring no material components: At will: detect magic, fog cloud, light; 3/day each: feather fall, fly, misty step, telekinesis; 1/day each: control weather, gaseous form"}]\n\n### Actions\n[{"name": "Multiattack", "description": "The giant makes two morningstar attacks."}, {"name": "Morningstar", "description": "Melee Weapon Attack: +12 to hit, reach 10 ft., one target. Hit: 21 (3d8 + 8) piercing damage.", "attack_bonus": 12, "damage_dice": "3d8+8", "damage_type": "piercing"}, {"name": "Rock", "description": "Ranged Weapon Attack: +12 to hit, range 60/240 ft., one target. Hit: 30 (4d10 + 8) bludgeoning damage.", "attack_bonus": 12, "damage_dice": "4d10+8", "damage_type": "bludgeoning"}]',
  size: 'Huge',
  type: 'giant',
  alignment: 'neutral good (50%) or neutral evil (50%)',
  level: 9,
  ac: 14,
  hp: 200,
  hit_dice: '16d12+96',
  challenge_rating: 9,
  xp: 5000,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 40,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: ['con', 'wis', 'cha'],
    skills: [],
    passivePerception: 17,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  inventory: [
    {
      item: 'morningstar',
      quantity: 1,
      slot: 'main_hand',
      isEquipped: true,
    },
  ],
  actions: ['cloud-giant-innate-spellcasting', 'cloud-giant-keen-smell', 'cloud-giant-multiattack', 'cloud-giant-rock'],
  spells: [
    'control-weather',
    'detect-magic',
    'feather-fall',
    'fly',
    'fog-cloud',
    'gaseous-form',
    'light',
    'misty-step',
    'telekinesis',
  ],
});
