import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'death-dog',
  name: 'Death Dog',
  description:
    '### Special Abilities\n[{"name":"Two-Headed","description":"The dog has advantage on Wisdom (Perception) checks and on saving throws against being blinded, charmed, deafened, frightened, stunned, or knocked unconscious."}]\n\n### Actions\n[{"name":"Multiattack","description":"The dog makes two bite attacks."},{"name":"Bite","description":"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage. If the target is a creature, it must succeed on a DC 12 Constitution saving throw against disease or become poisoned until the disease is cured. Every 24 hours that elapse, the creature must repeat the saving throw, reducing its hit point maximum by 5 (1d10) on a failure. This reduction lasts until the disease is cured. The creature dies if the disease reduces its hit point maximum to 0."}]',
  size: 'Medium',
  type: 'monstrosity',
  alignment: 'neutral evil',
  level: 1,
  ac: 12,
  hp: 39,
  hit_dice: '6d8+12',
  challenge_rating: 1,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 40,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 15,
    darkvision: 120,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: ['death-dog-bite', 'death-dog-multiattack', 'death-dog-two-headed'],
});
