import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'drider',
  name: 'Drider',
  description:
    '### Special Abilities\n[{"name":"Fey Ancestry","desc":"The drider has advantage on saving throws against being charmed, and magic can\'t put the drider to sleep."},{"name":"Innate Spellcasting","desc":"The drider\'s innate spellcasting ability is Wisdom (spell save DC 13). The drider can innately cast the following spells, requiring no material components: At will: dancing lights; 1/day each: darkness, faerie fire"},{"name":"Spider Climb","desc":"The drider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."},{"name":"Sunlight Sensitivity","desc":"While in sunlight, the drider has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."},{"name":"Web Walker","desc":"The drider ignores movement restrictions caused by webbing."}]\n\n### Actions\n[{"name":"Multiattack","desc":"The drider makes three attacks, either with its longsword or its longbow. It can replace one of those attacks with a bite attack."},{"name":"Bite","desc":"Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 2 (1d4) piercing damage plus 9 (2d8) poison damage.","attack_bonus":6,"damage":[{"type":"piercing","dice":"1d4"},{"type":"poison","dice":"2d8"}]},{"name":"Longsword","desc":"Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) slashing damage, or 8 (1d10 + 3) slashing damage if used with two hands.","attack_bonus":6,"damage":[{"type":"slashing","dice":"1d8+3"}]},{"name":"Longbow","desc":"Ranged Weapon Attack: +6 to hit, range 150/600 ft., one target. Hit: 7 (1d8 + 3) piercing damage plus 4 (1d8) poison damage.","attack_bonus":6,"damage":[{"type":"piercing","dice":"1d8+3"},{"type":"poison","dice":"1d8"}]}]',
  size: 'Large',
  type: 'monstrosity',
  alignment: 'chaotic evil',
  level: 6,
  ac: 19,
  hp: 123,
  hit_dice: '13d10+52',
  challenge_rating: 6,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 15,
    darkvision: 120,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  inventory: [
    {
      item: 'longbow',
      quantity: 1,
      slot: 'main_hand',
      isEquipped: true,
    },
    {
      item: 'longsword',
      quantity: 1,
      slot: 'backpack',
      isEquipped: false,
    },
  ],
  actions: [
    'drider-bite',
    'drider-dancing-lights',
    'drider-darkness',
    'drider-faerie-fire',
    'drider-fey-ancestry',
    'drider-innate-spellcasting',
    'drider-multiattack',
    'drider-spider-climb',
    'drider-sunlight-sensitivity',
    'drider-web-walker',
  ],
  spells: ['dancing-lights', 'darkness', 'faerie-fire'],
});
