import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'eagle',
  name: 'Eagle',
  description:
    '### Special Abilities\n[{"name":"Keen Sight","desc":"The eagle has advantage on Wisdom (Perception) checks that rely on sight."}]\n\n### Actions\n[{"name":"Talons","desc":"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) slashing damage.","attack_bonus":4,"damage":[{"damage_type":"bludgeoning","damage_dice":"1d4+2"}]}]',
  size: 'Small',
  type: 'beast',
  alignment: 'unaligned',
  level: 1,
  ac: 12,
  hp: 3,
  hit_dice: '1d6',
  challenge_rating: 0,
  xp: 10,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 10,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 0,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: ['eagle-keen-sight', 'eagle-talons'],
});
