import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'elephant',
  name: 'Elephant',
  description:
    '### Actions\n[{"name":"Gore","desc":"Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 19 (3d8 + 6) piercing damage.","attack_bonus":8,"damage_dice":"3d8+6"},{"name":"Stomp","desc":"Melee Weapon Attack: +8 to hit, reach 5 ft., one prone creature. Hit: 22 (3d10 + 6) bludgeoning damage.","attack_bonus":8,"damage_dice":"3d10+6"}]',
  size: 'Huge',
  type: 'beast',
  alignment: 'unaligned',
  level: 4,
  ac: 12,
  hp: 76,
  hit_dice: '8d12+24',
  challenge_rating: 4,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 40,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 10,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: ['elephant-gore', 'elephant-stomp'],
});
