import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'giant-crocodile',
  name: 'Giant Crocodile',
  description:
    '### Special Abilities\n[{"name":"Hold Breath","desc":"The crocodile can hold its breath for 30 minutes."}]\n\n### Actions\n[{"name":"Multiattack","desc":"The crocodile makes two attacks: one with its bite and one with its tail."},{"name":"Bite","desc":"Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 21 (3d10 + 5) piercing damage, and the target is grappled (escape DC 16). Until this grapple ends, the target is restrained, and the crocodile can\'t bite another target.","attack_bonus":8,"damage":[{"damage_type":{"index":"piercing","name":"Piercing","url":"/api/2014/damage-types/piercing"},"damage_dice":"3d10+5"}]},{"name":"Tail","desc":"Melee Weapon Attack: +8 to hit, reach 10 ft., one target not grappled by the crocodile. Hit: 14 (2d8 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 16 Strength saving throw or be knocked prone.","attack_bonus":8,"damage":[{"damage_type":{"index":"bludgeoning","name":"Bludgeoning","url":"/api/2014/damage-types/bludgeoning"},"damage_dice":"2d8+5"}]}]',
  size: 'Huge',
  type: 'beast',
  alignment: 'unaligned',
  level: 5,
  ac: 14,
  hp: 85,
  hit_dice: '9d12',
  challenge_rating: 5,
  xp: 1800,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 0,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: [
    'giant-crocodile-bite',
    'giant-crocodile-hold-breath',
    'giant-crocodile-multiattack',
    'giant-crocodile-tail',
  ],
});
