import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'gnoll',
  name: 'Gnoll',
  description:
    '### Special Abilities\n[{"name": "Rampage", "desc": "When the gnoll reduces a creature to 0 hit points with a melee attack on its turn, the gnoll can take a bonus action to move up to half its speed and make a bite attack."}]\n\n### Actions\n[{"name": "Bite", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 4 (1d4 + 2) piercing damage.", "attack_bonus": 4, "damage_dice": "1d4+2"}, {"name": "Spear", "desc": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 5 (1d6 + 2) piercing damage, or 6 (1d8 + 2) piercing damage if used with two hands to make a melee attack.", "attack_bonus": 4}, {"name": "Longbow", "desc": "Ranged Weapon Attack: +3 to hit, range 150/600 ft., one target. Hit: 5 (1d8 + 1) piercing damage.", "attack_bonus": 3, "damage_dice": "1d8+1"}]',
  size: 'Medium',
  type: 'humanoid',
  alignment: 'chaotic evil',
  level: 1,
  ac: 15,
  hp: 22,
  hit_dice: '5d8',
  challenge_rating: 0.5,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 10,
    darkvision: 60,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  inventory: [
    {
      item: 'longbow',
      quantity: 1,
      slot: 'main_hand',
      isEquipped: true,
    },
    {
      item: 'spear',
      quantity: 1,
      slot: 'backpack',
      isEquipped: false,
    },
  ],
  actions: ['gnoll-bite', 'gnoll-rampage'],
});
