import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'goblin',
  name: 'Goblin',
  description:
    '### Special Abilities\n[{"name":"Nimble Escape","desc":"The goblin can take the Disengage or Hide action as a bonus action on each of its turns."}]\n\n### Actions\n[{"name":"Scimitar","desc":"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.","attack_bonus":4,"damage_dice":"1d6+2"},{"name":"Shortbow","desc":"Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.","attack_bonus":4,"damage_dice":"1d6+2"}]',
  size: 'Small',
  type: 'humanoid',
  alignment: 'neutral evil',
  level: 1,
  ac: 15,
  hp: 7,
  hit_dice: '2d6',
  challenge_rating: 0.25,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 9,
    darkvision: 60,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  inventory: [
    {
      item: 'scimitar',
      quantity: 1,
      slot: 'main_hand',
      isEquipped: true,
    },
    {
      item: 'shortbow',
      quantity: 1,
      slot: 'backpack',
      isEquipped: false,
    },
  ],
  actions: ['goblin-nimble-escape'],
});
