import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'green-dragon-wyrmling',
  name: 'Green Dragon Wyrmling',
  description:
    '### Special Abilities\n["{\\"name\\":\\"Amphibious\\",\\"description\\":\\"The dragon can breathe air and water.\\"}"]\n\n### Actions\n["{\\"name\\":\\"Bite\\",\\"description\\":\\"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10 + 2) piercing damage plus 3 (1d6) poison damage.\\",\\"attack_bonus\\":4,\\"damage\\":[{\\"type\\":\\"piercing\\",\\"dice\\":\\"1d10+2\\"},{\\"type\\":\\"poison\\",\\"dice\\":\\"1d6\\"}]}","{\\"name\\":\\"Poison Breath\\",\\"description\\":\\"The dragon exhales poisonous gas in a 15-foot cone. Each creature in that area must make a DC 11 Constitution saving throw, taking 21 (6d6) poison damage on a failed save, or half as much damage on a successful one.\\",\\"recharge\\":\\"5-6\\",\\"dc\\":{\\"type\\":\\"con\\",\\"value\\":11}}"]',
  size: 'Medium',
  type: 'dragon',
  alignment: 'lawful evil',
  level: 2,
  ac: 17,
  hp: 38,
  hit_dice: '7d8+7',
  challenge_rating: 2,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: ['dex', 'con', 'wis', 'cha'],
    skills: [],
    passivePerception: 14,
    darkvision: 60,
    blindsight: 10,
    truesight: 0,
    tremorsense: 0,
  },
  actions: ['green-dragon-wyrmling-amphibious', 'green-dragon-wyrmling-bite', 'green-dragon-wyrmling-poison-breath'],
});
