import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'horned-devil',
  name: 'Horned Devil',
  description:
    '### Special Abilities\n["Devil\'s Sight: Magical darkness doesn\'t impede the devil\'s darkvision.","Magic Resistance: The devil has advantage on saving throws against spells and other magical effects."]\n\n### Actions\n["Multiattack: The devil makes three melee attacks: two with its fork and one with its tail. It can use Hurl Flame in place of any melee attack.","Fork: Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 15 (2d8 + 6) piercing damage.","Tail: Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 10 (1d8 + 6) piercing damage. If the target is a creature other than an undead or a construct, it must succeed on a DC 17 Constitution saving throw or lose 10 (3d6) hit points at the start of each of its turns due to an infernal wound. Each time the devil hits the wounded target with this attack, the damage dealt by the wound increases by 10 (3d6). Any creature can take an action to stanch the wound with a successful DC 12 Wisdom (Medicine) check. The wound also closes if the target receives magical healing.","Hurl Flame: Ranged Spell Attack: +7 to hit, range 150 ft., one target. Hit: 14 (4d6) fire damage. If the target is a flammable object that isn\'t being worn or carried, it also catches fire."]',
  size: 'Large',
  type: 'fiend',
  alignment: 'lawful evil',
  level: 11,
  ac: 18,
  hp: 178,
  hit_dice: '17d10',
  challenge_rating: 11,
  xp: 7200,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 0,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: ['str', 'dex', 'wis', 'cha'],
    skills: [],
    passivePerception: 13,
    darkvision: 120,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: [
    'horned-devil-devil-s-sight',
    'horned-devil-fork',
    'horned-devil-hurl-flame',
    'horned-devil-magic-resistance',
    'horned-devil-multiattack',
    'horned-devil-tail',
  ],
});
