import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'merrow',
  name: 'Merrow',
  description:
    '### Special Abilities\n["Amphibious: The merrow can breathe air and water."]\n\n### Actions\n["Multiattack: The merrow makes two attacks: one with its bite and one with its claws or harpoon.","Bite: Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.","Claws: Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 9 (2d4 + 4) slashing damage.","Harpoon: Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 11 (2d6 + 4) piercing damage. If the target is a Huge or smaller creature, it must succeed on a Strength contest against the merrow or be pulled up to 20 feet toward the merrow."]',
  size: 'Large',
  type: 'monstrosity',
  alignment: 'chaotic evil',
  level: 2,
  ac: 13,
  hp: 45,
  hit_dice: '6d10+12',
  challenge_rating: 2,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 10,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 10,
    darkvision: 60,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: ['merrow-amphibious', 'merrow-bite', 'merrow-claws', 'merrow-harpoon', 'merrow-multiattack'],
});
