import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'pony',
  name: 'Pony',
  description:
    '### Actions\n[{"name":"Hooves","desc":"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) bludgeoning damage.","attack_bonus":4,"damage":[{"damage_type":"bludgeoning","damage_dice":"2d4+2"}]}]',
  size: 'Medium',
  type: 'beast',
  alignment: 'unaligned',
  level: 1,
  ac: 10,
  hp: 11,
  hit_dice: '2d8',
  challenge_rating: 0.125,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 40,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 0,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: ['pony-hooves'],
});
