import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'weasel',
  name: 'Weasel',
  description:
    '### Special Abilities\n["Keen Hearing and Smell: The weasel has advantage on Wisdom (Perception) checks that rely on hearing or smell."]\n\n### Actions\n["Bite: Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 1 piercing damage."]',
  size: 'Tiny',
  type: 'beast',
  alignment: 'unaligned',
  level: 1,
  ac: 13,
  hp: 1,
  hit_dice: '1d4',
  challenge_rating: 0,
  xp: 10,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 13,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: ['weasel-bite', 'weasel-keen-hearing-and-smell'],
});
