import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'weretiger-human',
  name: 'Weretiger Human',
  size: 'Medium',
  type: 'unknown',
  alignment: 'unaligned',
  level: 1,
  ac: 10,
  hp: 10,
  challenge_rating: 0,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 0,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 0,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  inventory: [
    {
      item: 'longbow',
      quantity: 1,
      slot: 'main_hand',
      isEquipped: true,
    },
    {
      item: 'scimitar',
      quantity: 1,
      slot: 'backpack',
      isEquipped: false,
    },
  ],
  actions: ['weretiger-human-keen-hearing-and-smell', 'weretiger-human-multiattack', 'weretiger-human-shapechanger'],
});
