import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'weretiger-hybrid',
  name: 'Weretiger, Hybrid Form',
  description:
    "### Special Abilities\nThe weretiger can use its action to polymorph into a tiger-humanoid hybrid or into a tiger, or back into its true form, which is humanoid. Its statistics, other than its size, are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies.\n\n### Actions\nIn humanoid form, the weretiger makes two scimitar attacks or two longbow attacks. In hybrid form, it can attack like a humanoid or make two claw attacks.",
  size: 'Medium',
  type: 'humanoid',
  alignment: 'neutral',
  level: 4,
  ac: 12,
  hp: 120,
  hit_dice: '16d8+48',
  challenge_rating: 4,
  xp: 1100,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 0,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: [
    'weretiger-hybrid-claw-attack',
    'weretiger-hybrid-longbow-attack',
    'weretiger-hybrid-polymorph',
    'weretiger-hybrid-scimitar-attack',
  ],
});
