import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'wight',
  name: 'Wight',
  description:
    '### Special Abilities\n[{"name":"Sunlight Sensitivity","desc":"While in sunlight, the wight has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."}]\n\n### Actions\n[{"name":"Multiattack","desc":"The wight makes two longsword attacks or two longbow attacks. It can use its Life Drain in place of one longsword attack."},{"name":"Life Drain","desc":"Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6 + 2) necrotic damage. The target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken. This reduction lasts until the target finishes a long rest. The target dies if this effect reduces its hit point maximum to 0.\\nA humanoid slain by this attack rises 24 hours later as a zombie under the wight\'s control, unless the humanoid is restored to life or its body is destroyed. The wight can have no more than twelve zombies under its control at one time."},{"name":"Longsword","desc":"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) slashing damage, or 7 (1d10 + 2) slashing damage if used with two hands."},{"name":"Longbow","desc":"Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8 + 2) piercing damage."}]',
  size: 'Medium',
  type: 'undead',
  alignment: 'neutral evil',
  level: 3,
  ac: 14,
  hp: 45,
  hit_dice: '6d8',
  challenge_rating: 3,
  xp: 700,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 30,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: [],
    skills: [],
    passivePerception: 0,
    darkvision: 0,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  inventory: [
    {
      item: 'longbow',
      quantity: 1,
      slot: 'main_hand',
      isEquipped: true,
    },
    {
      item: 'longsword',
      quantity: 1,
      slot: 'backpack',
      isEquipped: false,
    },
  ],
  actions: ['wight-life-drain', 'wight-multiattack', 'wight-sunlight-sensitivity'],
});
