import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'will-o-wisp',
  name: "Will-o'-Wisp",
  description:
    '### Special Abilities\n[{"name":"Consume Life","description":"As a bonus action, the will-o\'-wisp can target one creature it can see within 5 ft. of it that has 0 hit points and is still alive. The target must succeed on a DC 10 Constitution saving throw against this magic or die. If the target dies, the will-o\'-wisp regains 10 (3d6) hit points."},{"name":"Ephemeral","description":"The will-o\'-wisp can\'t wear or carry anything."},{"name":"Incorporeal Movement","description":"The will-o\'-wisp can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object."},{"name":"Variable Illumination","description":"The will-o\'-wisp sheds bright light in a 5- to 20-foot radius and dim light for an additional number of ft. equal to the chosen radius. The will-o\'-wisp can alter the radius as a bonus action."}]\n\n### Actions\n[{"name":"Shock","description":"Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 9 (2d8) lightning damage."},{"name":"Invisibility","description":"The will-o\'-wisp and its light magically become invisible until it attacks or uses its Consume Life, or until its concentration ends (as if concentrating on a spell)."}]',
  size: 'Tiny',
  type: 'undead',
  alignment: 'chaotic evil',
  level: 2,
  ac: 19,
  hp: 22,
  hit_dice: '9d4',
  challenge_rating: 2,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 0,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: true,
    saves: [],
    skills: [],
    passivePerception: 12,
    darkvision: 120,
    blindsight: 0,
    truesight: 0,
    tremorsense: 0,
  },
  actions: [
    'will-o-wisp-consume-life',
    'will-o-wisp-ephemeral',
    'will-o-wisp-incorporeal-movement',
    'will-o-wisp-invisibility',
    'will-o-wisp-shock',
    'will-o-wisp-variable-illumination',
  ],
});
