import { defineEntity } from '@/features/genesis-core/blueprints';

export default defineEntity({
  slug: 'young-bronze-dragon',
  name: 'Young Bronze Dragon',
  description:
    '### Special Abilities\n[{"name":"Amphibious","description":"The dragon can breathe air and water."}]\n\n### Actions\n[{"name":"Multiattack","description":"The dragon makes three attacks: one with its bite and two with its claws."},{"name":"Bite","description":"Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 16 (2d10 + 5) piercing damage."},{"name":"Claw","description":"Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 12 (2d6 + 5) slashing damage."},{"name":"Breath Weapons (Recharge 5-6)","description":"The dragon uses one of the following breath weapons. Lightning Breath. The dragon exhales lightning in a 60-foot line that is 5 feet wide. Each creature in that line must make a DC 15 Dexterity saving throw, taking 55 (10d10) lightning damage on a failed save, or half as much damage on a successful one. Repulsion Breath. The dragon exhales repulsion energy in a 30-foot cone. Each creature in that area must succeed on a DC 15 Strength saving throw. On a failed save, the creature is pushed 40 feet away from the dragon."}]',
  size: 'Large',
  type: 'dragon',
  alignment: 'lawful good',
  level: 8,
  ac: 18,
  hp: 142,
  hit_dice: '15d10+60',
  challenge_rating: 8,
  xp: 0,
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    walkSpeed: 40,
    flySpeed: 0,
    swimSpeed: 0,
    climbSpeed: 0,
    burrowSpeed: 0,
    hover: false,
    saves: ['dex', 'con', 'wis', 'cha'],
    skills: [],
    passivePerception: 17,
    darkvision: 120,
    blindsight: 30,
    truesight: 0,
    tremorsense: 0,
  },
  actions: [
    'young-bronze-dragon-amphibious',
    'young-bronze-dragon-bite',
    'young-bronze-dragon-claw',
    'young-bronze-dragon-lightning-breath',
    'young-bronze-dragon-multiattack',
    'young-bronze-dragon-repulsion-breath',
  ],
});
