export const TAG_ATOMS = [
  // --- Terrains / Biomes ---
  { name: 'Arctic', type: 'terrain', color: '#A5F2F3' },
  { name: 'Coastal', type: 'terrain', color: '#4ECDC4' },
  { name: 'Desert', type: 'terrain', color: '#FFE66D' },
  { name: 'Forest', type: 'terrain', color: '#556B2F' },
  { name: 'Grassland', type: 'terrain', color: '#9ACD32' },
  { name: 'Hill', type: 'terrain', color: '#808000' },
  { name: 'Mountain', type: 'terrain', color: '#8B4513' },
  { name: 'Swamp', type: 'terrain', color: '#2E8B57' },
  { name: 'Underdark', type: 'terrain', color: '#800080' },
  { name: 'Underwater', type: 'terrain', color: '#000080' },
  { name: 'Urban', type: 'terrain', color: '#778899' },

  // --- Magic Schools ---
  { name: 'Abjuration', type: 'school', color: '#6495ED' },
  { name: 'Conjuration', type: 'school', color: '#FFD700' },
  { name: 'Divination', type: 'school', color: '#C0C0C0' },
  { name: 'Enchantment', type: 'school', color: '#FF69B4' },
  { name: 'Evocation', type: 'school', color: '#FF4500' },
  { name: 'Illusion', type: 'school', color: '#9370DB' },
  { name: 'Necromancy', type: 'school', color: '#2F4F4F' },
  { name: 'Transmutation', type: 'school', color: '#32CD32' },

  // --- Languages ---
  { name: 'Common', type: 'language', color: '#D3D3D3' },
  { name: 'Dwarvish', type: 'language', color: '#A9A9A9' },
  { name: 'Elvish', type: 'language', color: '#90EE90' },
  { name: 'Giant', type: 'language', color: '#8B0000' },
  { name: 'Gnomish', type: 'language', color: '#DEB887' },
  { name: 'Goblin', type: 'language', color: '#556B2F' },
  { name: 'Halfling', type: 'language', color: '#F0E68C' },
  { name: 'Orc', type: 'language', color: '#696969' },
  { name: 'Abyssal', type: 'language', color: '#800000' },
  { name: 'Celestial', type: 'language', color: '#FFFFFF' },
  { name: 'Draconic', type: 'language', color: '#B8860B' },
  { name: 'Deep Speech', type: 'language', color: '#4B0082' },
  { name: 'Infernal', type: 'language', color: '#8B0000' },
  { name: 'Primordial', type: 'language', color: '#008B8B' },
  { name: 'Sylvan', type: 'language', color: '#228B22' },
  { name: 'Undercommon', type: 'language', color: '#483D8B' },

  // --- Damage Types ---
  { name: 'Acid', type: 'damage', color: '#7FFF00' },
  { name: 'Bludgeoning', type: 'damage', color: '#808080' },
  { name: 'Cold', type: 'damage', color: '#00FFFF' },
  { name: 'Fire', type: 'damage', color: '#FF0000' },
  { name: 'Force', type: 'damage', color: '#FFFFFF' },
  { name: 'Lightning', type: 'damage', color: '#FFFF00' },
  { name: 'Necrotic', type: 'damage', color: '#000000' },
  { name: 'Piercing', type: 'damage', color: '#A9A9A9' },
  { name: 'Poison', type: 'damage', color: '#00FF7F' },
  { name: 'Psychic', type: 'damage', color: '#FF1493' },
  { name: 'Radiant', type: 'damage', color: '#FFD700' },
  { name: 'Slashing', type: 'damage', color: '#C0C0C0' },
  { name: 'Thunder', type: 'damage', color: '#1E90FF' },

  // --- Conditions ---
  { name: 'Blinded', type: 'condition', color: '#696969' },
  { name: 'Charmed', type: 'condition', color: '#FF69B4' },
  { name: 'Deafened', type: 'condition', color: '#A9A9A9' },
  { name: 'Exhaustion', type: 'condition', color: '#8B4513' },
  { name: 'Frightened', type: 'condition', color: '#4B0082' },
  { name: 'Grappled', type: 'condition', color: '#800000' },
  { name: 'Incapacitated', type: 'condition', color: '#808080' },
  { name: 'Invisible', type: 'condition', color: '#F0F8FF' },
  { name: 'Paralyzed', type: 'condition', color: '#FFFF00' },
  { name: 'Petrified', type: 'condition', color: '#708090' },
  { name: 'Poisoned', type: 'condition', color: '#00FF7F' },
  { name: 'Prone', type: 'condition', color: '#D2691E' },
  { name: 'Restrained', type: 'condition', color: '#8B0000' },
  { name: 'Stunned', type: 'condition', color: '#FFFFE0' },
  { name: 'Unconscious', type: 'condition', color: '#000000' },

  // --- Sizes ---
  { name: 'Tiny', type: 'size', color: '#E0FFFF' },
  { name: 'Small', type: 'size', color: '#ADD8E6' },
  { name: 'Medium', type: 'size', color: '#87CEEB' },
  { name: 'Large', type: 'size', color: '#4682B4' },
  { name: 'Huge', type: 'size', color: '#000080' },
  { name: 'Gargantuan', type: 'size', color: '#191970' },

  // --- Alignments ---
  { name: 'Lawful Good', type: 'alignment', color: '#FFFACD' },
  { name: 'Neutral Good', type: 'alignment', color: '#F0FFF0' },
  { name: 'Chaotic Good', type: 'alignment', color: '#F5FFFA' },
  { name: 'Lawful Neutral', type: 'alignment', color: '#D3D3D3' },
  { name: 'Neutral', type: 'alignment', color: '#A9A9A9' },
  { name: 'Chaotic Neutral', type: 'alignment', color: '#808080' },
  { name: 'Lawful Evil', type: 'alignment', color: '#B22222' },
  { name: 'Neutral Evil', type: 'alignment', color: '#800000' },
  { name: 'Chaotic Evil', type: 'alignment', color: '#FF0000' },
  { name: 'Unaligned', type: 'alignment', color: '#778899' },

  // --- Rarities ---
  { name: 'Common', type: 'rarity', color: '#D3D3D3' },
  { name: 'Uncommon', type: 'rarity', color: '#32CD32' },
  { name: 'Rare', type: 'rarity', color: '#00BFFF' },
  { name: 'Very Rare', type: 'rarity', color: '#9400D3' },
  { name: 'Legendary', type: 'rarity', color: '#FFD700' },
  { name: 'Artifact', type: 'rarity', color: '#FF4500' },

  // --- Mechanic Types ---
  { name: 'Mechanic', type: 'mechanic', color: '#708090' },
  { name: 'Visual', type: 'visual', color: '#FF1493' },
  { name: 'Meta', type: 'meta', color: '#000000' },
  { name: 'Weapon', type: 'mechanic', color: '#A52A2A' },
  { name: 'Armor', type: 'mechanic', color: '#708090' },
  { name: 'Potion', type: 'mechanic', color: '#FF69B4' },
  { name: 'Scroll', type: 'mechanic', color: '#F0E68C' },
  { name: 'Wondrous Item', type: 'mechanic', color: '#9370DB' },
  { name: 'Ring', type: 'mechanic', color: '#FFD700' },
  { name: 'Rod', type: 'mechanic', color: '#8B4513' },
  { name: 'Staff', type: 'mechanic', color: '#8B4513' },
  { name: 'Wand', type: 'mechanic', color: '#D2691E' },
  { name: 'Tool', type: 'mechanic', color: '#808080' },

  // --- Skills ---
  { name: 'Athletics', type: 'mechanic', color: '#CD5C5C' },
  { name: 'Acrobatics', type: 'mechanic', color: '#FFA07A' },
  { name: 'Sleight of Hand', type: 'mechanic', color: '#ffa500' },
  { name: 'Stealth', type: 'mechanic', color: '#2F4F4F' },
  { name: 'Arcana', type: 'mechanic', color: '#8A2BE2' },
  { name: 'History', type: 'mechanic', color: '#8B4513' },
  { name: 'Investigation', type: 'mechanic', color: '#4682B4' },
  { name: 'Nature', type: 'mechanic', color: '#228B22' },
  { name: 'Religion', type: 'mechanic', color: '#FFD700' },
  { name: 'Animal Handling', type: 'mechanic', color: '#F4A460' },
  { name: 'Insight', type: 'mechanic', color: '#9370DB' },
  { name: 'Medicine', type: 'mechanic', color: '#00CED1' },
  { name: 'Perception', type: 'mechanic', color: '#FF8C00' },
  { name: 'Survival', type: 'mechanic', color: '#556B2F' },
  { name: 'Deception', type: 'mechanic', color: '#800080' },
  { name: 'Intimidation', type: 'mechanic', color: '#8B0000' },
  { name: 'Performance', type: 'mechanic', color: '#FF69B4' },
  { name: 'Persuasion', type: 'mechanic', color: '#1E90FF' },

  // --- Monster Types ---
  { name: 'Aberration', type: 'mechanic', color: '#800080' },
  { name: 'Beast', type: 'mechanic', color: '#8B4513' },
  { name: 'Celestial', type: 'mechanic', color: '#FFFF00' },
  { name: 'Construct', type: 'mechanic', color: '#808080' },
  { name: 'Dragon', type: 'mechanic', color: '#B22222' },
  { name: 'Elemental', type: 'mechanic', color: '#FF4500' },
  { name: 'Fey', type: 'mechanic', color: '#FF69B4' },
  { name: 'Fiend', type: 'mechanic', color: '#8B0000' },
  { name: 'Giant', type: 'mechanic', color: '#A9A9A9' },
  { name: 'Humanoid', type: 'mechanic', color: '#D2B48C' },
  { name: 'Monstrosity', type: 'mechanic', color: '#2F4F4F' },
  { name: 'Ooze', type: 'mechanic', color: '#00FF00' },
  { name: 'Plant', type: 'mechanic', color: '#008000' },
  { name: 'Undead', type: 'mechanic', color: '#4B0082' },
];
