import { defineBlueprint } from '@/features/genesis-core/blueprints';

const grid = [
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                HHHHHHHHH                                       ",
  "               HHHHHHHHHHH                                      ",
  "               HHHHHHHHHHH                                      ",
  "               HHHHHHHHHHH                                      ",
  "              HHHHHHHHHHHHH                                     ",
  "              HHHHHHHHHHHHH   bbbbbbbbbb..                      ",
  "              HHHHHHHHHHHHH bbbbbbbbbbbbbbb...                  ",
  "               HHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbb                 ",
  "               HHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbbb                ",
  "                HHHHHHHHH bbbbbbbbbbbbbbbbbbbbbbb               ",
  "                          bbbbbbbbbbbbbbbbbbbbbbbb              ",
  "                          bbbbbbbbbbbbbbbbbbbbbbbbb             ",
  "                          bbbbbbbbbbbbbbbbbbbbbbbbb             ",
  "                          bbbbbbbbbbbbbbbbbbbbbbbbb             ",
  "                         bbbbbbbbbbbbbbbbbbbbbbbbbb             ",
  "                         bbbbbbbbbbbbbbbbbbbbbbbbbb             ",
  "                         bbbbbbbbbbbbbbbbbbbbbbbbbb             ",
  "                         bbbbbbbbbbbbbbbbbbbbbbbbbb             ",
  "                        bbbbbbbbbbbbbbbbbbbbbbbbbb              ",
  "                        bbbbbbbbbbbbbbbbbbbbbbbbb               ",
  "                        bbbbbbbbbbbbbbbbbbbbbbbb                ",
  "                       bbbbbbbbbbbbbbbbbbbbbbbbb                ",
  "                      bbbbbbbbbbbbbbbbbbbbbbbbb                 ",
  "                     bbbbbbbbbbbbbbbbbbbbbbbbb                  ",
  "                   bbbbbbbbbbbbbbbbbbbbbbbbbb                   ",
  "                 bbbbbbbbbbbbbbbbbbbbbbbbbbb                    ",
  "              bbbbbbbbbbbbbbbbbbbbbbbbbbbbb                     ",
  "           bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                      ",
  "         bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb          TTTT         ",
  "        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb        TTTTTTTTT       ",
  "       bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb      TTTTTTTTTTTT      ",
  "      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb    TTTTTTTTTTTTTTT     ",
  "      bbbbbbbbbbbbbb   bbbbbbbbbbbbbbbbbb  TTTTTTTTTTTTTTTTT    ",
  "     bbbbbbbbbbbb       bbbbbbbbbbbbbbbbb TTTTTTTTTTTTTTTTTT    ",
  "     bbbbbbbbbbb         bbbbbbbbbbbbbbbbTTTTTTTTTTTTTTTTTTT    ",
  "     bbbbbbbbbb          bbbbbbbbbbbbbbbbTTTTTTTTTTTTTTTTTTT    ",
  "      bbbbbbbb            bbbbbbbbbbbbbbbTTTTTTTTTTTTTTTTTTT    ",
  "                           bbbbbbbbbbbbbb TTTTTTTTTTTTTTTTT     ",
  "                            bbbbbbbbbbbb   TTTTTTTTTTTTTTT      ",
  "                             bbbbbbbbbb      TTTTTTTTTTT        ",
  "                                                             ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                "
].map(row => row.split(''));

export default defineBlueprint({
  name: 'Serpent (Large)',
  slug: 'serpent-large',
  category: 'Creature',
  grid,
  zones: ["head","body","tail"],
  mapping: {
    "H": "head",
    "b": "body",
    "T": "tail"
  },
  anchors: {
    "head": [32, 10],
    "body": [32, 32],
    "tail": [32, 54]
  }
});
