import { GoogleGenAI } from '@google/genai';
import { ImageProcessor } from './image-processor';

export class ImageGenerator {
  /**
   * Generates a square pixel art sprite utilizing Gemini 3.1 Flash Image.
   * Leverages the `ImageProcessor` to enforce D&D strict-grid sizes & quantize the palette.
   *
   * @param opts Generation configuration including entity data context.
   * @returns Raw Image, Quantized Image, and 1D/2D Hex Matrices for Map Explorer.
   */
  static async generate(opts: {
    prompt: string;
    size: number;
    blueprintMatrix?: string[][]; // Injected Silhouette
    inputPixels?: string[][]; // Injected existing state
    contextData?: string; // Additional LLM lore data or context
  }): Promise<{ base64Original: string; base64Processed: string; hexArray: string[][] }> {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('GEMINI_API_KEY not configured');

    const ai = new GoogleGenAI({ apiKey });

    // Enforce 32x32 Grid Scale Concept per the User's Proof of Concept rules
    const scaleContext = `In this world's scale, 32x32 pixels equals exactly 1 foot by 1 foot. This sprite will be rendered at ${opts.size}x${opts.size} pixels (which is ${opts.size / 32} feet by ${opts.size / 32} feet).`;
    const pixelContext = `Ensure the object's proportions fit this scale and the art style is heavily pixelated, blocky, and designed specifically for a strict ${opts.size}x${opts.size} grid.`;

    let fullPrompt = `A perfect square pixel art sprite of ${opts.prompt}. ${scaleContext} ${pixelContext} Medieval fantasy game style, retro, isolated on a pure solid white background, 2D flat, no shadows on the background, clean edges, centered.`;

    // Inject Schema/Entity exact Lore details if provided
    if (opts.contextData) {
      fullPrompt += `\nLORE / DETAILS: ${opts.contextData}`;
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const parts: any[] = [];

    // Replicate User's Blueprint Silhouette injection if provided
    if (opts.blueprintMatrix && opts.blueprintMatrix.length > 0) {
      const blueprintBase64 = await ImageProcessor.hexArrayToPng(opts.blueprintMatrix);
      if (blueprintBase64) {
        fullPrompt += ` Use the provided image as a loose blueprint or silhouette reference for orientation and shape, but generate a completely new highly detailed sprite.`;
        parts.push({
          inlineData: {
            data: blueprintBase64.split(',')[1],
            mimeType: 'image/png',
          },
        });
      }
    }

    if (opts.inputPixels && opts.inputPixels.length > 0) {
      const inputBase64 = await ImageProcessor.hexArrayToPng(opts.inputPixels);
      if (inputBase64) {
        fullPrompt += ` Use the provided second image as the CURRENT VISUAL STATE of the canvas. You must modify or extend this canvas according to the prompt exactly.`;
        parts.push({
          inlineData: {
            data: inputBase64.split(',')[1],
            mimeType: 'image/png',
          },
        });
      }
    }

    // Always append the text prompt at the very end structure
    parts.push({ text: fullPrompt });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const generateWithRetry = async (parts: any[], retries = 3, delay = 1000): Promise<any> => {
      try {
        return await ai.models.generateContent({
          model: 'gemini-3.1-flash-image-preview',
          contents: { parts },
          config: {
            imageConfig: {
              aspectRatio: '1:1',
              imageSize: '512px',
            },
          },
        });
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      } catch (err: any) {
        if (
          retries > 0 &&
          (err.status === 500 ||
            err.status === 503 ||
            err.message?.includes('500') ||
            err.message?.includes('503') ||
            err.message?.includes('timeout'))
        ) {
          await new Promise((resolve) => setTimeout(resolve, delay));
          return generateWithRetry(parts, retries - 1, delay * 2);
        }
        throw err;
      }
    };

    const response = await generateWithRetry(parts);

    let base64Image = null;
    if (response.candidates && response.candidates[0] && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          base64Image = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!base64Image) {
      throw new Error('No image was generated by the Gemini Imagen model.');
    }

    // Invoke exact quantizer pipeline
    const processedImage = await ImageProcessor.processImage(base64Image, opts.size);
    const hexArray = await ImageProcessor.toHexArray(processedImage, opts.size);

    return {
      base64Original: base64Image,
      base64Processed: processedImage,
      hexArray,
    };
  }
}
