
import dotenv from 'dotenv';
import path from 'path';
import type { 
/*
  ApiFeatureFeature, 
  ApiSpellSpell, 
  ApiItemItem, 
  ApiClassClass, 
  ApiDamageTypeDamageType,
  ApiMagicSchoolMagicSchool
*/
} from '../../../types/generated/contentTypes';
// We need to import Component types via Strapi's module augmentation or define compatible interfaces
// Since explicit imports from components.d.ts are not straightforward in a single file without alias config working perfectly in ts-node,
// We will define interfaces that MATCH the structure we saw in components.d.ts.
// This ensures strictness without fighting ts-node module resolution for generated files.
import { loadTags } from './tag-loader';

// Component Interfaces (Matching types/generated/components.d.ts)
interface GameFeatureComponent {
    name: string;
    description?: string;
    source?: 'class'; // Enum subset
    usage_max?: number;
    usage_per?: 'short_rest' | 'long_rest' | 'day' | 'dawn' | 'dusk' | 'other';
}

interface GameClassProgressionComponent {
    level: number;
    pb?: number; // Not in schema? Checked schema: 'pb' is NOT in attributes of GameClassProgression! Wait.
    // Schema has: class_specifics: JSON, features: Relation, level: Integer, spell_slots: JSON.
    // So 'pb' (Proficiency Bonus) must be calculated or stored in class_specifics? 
    // For now we will omit 'pb' if it's not in the schema.
    features?: string[]; // documentIds for Relation
}

// 1. Load Environment Variables
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

// 2. Define Strict Seed Data Interfaces (Matching compile-seeds output)
// These interfaces describe what is INSIDE the .ts seed files.
interface SeedFeature {
    slug: string;
    name: string;
    description: string;
    level: number | string;
    lore?: string;
}

interface SeedSpell {
    slug: string;
    name: string;
    level: number | string;
    school: string;
    description: string;
    lore?: string;
    casting_time?: string;
    range?: string;
    components?: string;
    duration?: string;
}

interface SeedItem {
    slug: string;
    name: string;
    rarity?: string;
    type?: string;
    description: string;
    lore?: string;
    requires_attunement?: boolean;
}

interface SeedClass {
    slug: string;
    name: string;
    hit_die: number | string;
    lore?: string;
    features?: string[]; // Array of slugs
    progression?: Array<{
        level: number;
        pb: number;
        features: string[];
    }>;
}

async function main() {
  console.log('✨  \x1b[1m\x1b[32mStarting Canonical Seeder (Strict Relational Ingest)...\x1b[0m\n');

  const backendRoot = path.resolve(__dirname, '../../..');
  process.chdir(backendRoot);

  const { createStrapi } = await import('@strapi/strapi');
  const strapi = await createStrapi({
    appDir: backendRoot,
    distDir: 'dist',
  }).load();

  try {
    // --- Load Seed Data ---
    console.log('📦 Loading TS Seed Data...');
    // We expect these to be generated by compile-seeds.ts
    const { FEATURES } = await import('../../genesis/seed-data/features');
    const { SPELLS } = await import('../../genesis/seed-data/spells');
    const { ITEMS } = await import('../../genesis/seed-data/items');
    const { CLASSES } = await import('../../genesis/seed-data/classes');
    const { TERRAINS } = await import('../../genesis/seed-data/terrains');
    
    // --- 0. Atoms: Layers (Tags, Damage, Schools) ---
    // Seed these first as they are dependencies.
    
    // Tags (The Foundation)
    await loadTags(strapi);

    // Damage Types
    const DAMAGE_TYPES = [
        'Acid', 'Bludgeoning', 'Cold', 'Fire', 'Force', 'Lightning', 'Necrotic', 'Piercing', 'Poison', 'Psychic', 'Radiant', 'Slashing', 'Thunder'
    ];
    console.log(`\n⚛️  Seeding ${DAMAGE_TYPES.length} Damage Types...`);
    for (const dt of DAMAGE_TYPES) {
        const slug = dt.toLowerCase();
        const existing = await strapi.documents('api::damage-type.damage-type').findFirst({ filters: { slug } });
        if (!existing) {
            await strapi.documents('api::damage-type.damage-type').create({
                data: {
                    name: dt,
                    slug,
                    description: `The ${dt} damage type.`,
                    publishedAt: new Date()
                }
            });
        }
    }

    // Magic Schools
    const MAGIC_SCHOOLS = [
        'Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation'
    ];
    console.log(`⚛️  Seeding ${MAGIC_SCHOOLS.length} Magic Schools...`);
    for (const ms of MAGIC_SCHOOLS) {
        const slug = ms.toLowerCase();
        const existing = await strapi.documents('api::magic-school.magic-school').findFirst({ filters: { slug } });
        if (!existing) {
            await strapi.documents('api::magic-school.magic-school').create({
                data: {
                    name: ms,
                    slug,
                    description: `The School of ${ms}.`,
                    publishedAt: new Date()
                }
            });
        }
    }

    // --- 0.1 Terrains (Atoms) ---
    console.log(`\n🌍 Seeding ${TERRAINS.length} Terrains...`);
    type TerrainSeedType = typeof TERRAINS[number]; 

    for (const rawData of TERRAINS) {
        const data = rawData as TerrainSeedType;
        
        const payload = {
            name: data.name,
            slug: data.slug,
            color: data.color,
            isWalkable: data.isWalkable,
            isTransparent: data.isTransparent,
            isLiquid: data.isLiquid,
            damagePerTick: data.damagePerTick,
            luminance: data.luminance,
            moisture: data.moisture,
            temperature: data.temperature,
            tags: data.tags,
            noise_config: data.noise_config ? { ...data.noise_config } : null,
            publishedAt: new Date()
        };

        const existing = await strapi.documents('api::terrain.terrain').findFirst({ filters: { slug: data.slug } });
        if (existing) {
             // For components, we often need to be careful. 
             // Strapi 5 Document Service handles components well, but let's be explicit.
             await strapi.documents('api::terrain.terrain').update({
                 documentId: existing.documentId,
                 data: payload
             });
        } else {
            await strapi.documents('api::terrain.terrain').create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Terrains Done.');

    // --- 1. Features (Atoms) ---
    console.log(`\n📚 Seeding ${FEATURES.length} features...`);
    for (const rawData of FEATURES) {
        const data = rawData as unknown as SeedFeature;
        
        const payload = {
            slug: data.slug,
            name: data.name,
            description: data.description,
            level: typeof data.level === 'string' ? parseInt(data.level) : data.level,
            // Only assign if strictly matching the expected boolean type or optional
            // is_subclass_feature is not in the schema we saw earlier in contentTypes.d.ts?
            // Checked schema: NO 'is_subclass_feature' in ApiFeatureFeature attributes!
            // It has: name, description, level, slug, lore, compilation_state, etc.
            // So we must OMIT is_subclass_feature.
            lore: data.lore || undefined,
            publishedAt: new Date()
        };

        const existing = await strapi.documents('api::feature.feature').findFirst({ filters: { slug: data.slug } });
        if (existing) {
             // Explicitly typed update
             await strapi.documents('api::feature.feature').update({
                 documentId: existing.documentId,
                 data: { 
                    description: payload.description, 
                    lore: payload.lore 
                 }
             });
        } else {
            await strapi.documents('api::feature.feature').create({
                data: payload
            });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Features Done.');

    // --- Helper Parsers ---

    function parseCastingConfig(raw?: string) {
        if (!raw) return null;
        const normalized = raw.toLowerCase().trim();
        // match "1 action", "10 minutes", "1 reaction"
        const match = normalized.match(/^(\d+)\s+(.+)$/);
        if (match) {
            let unit = match[2];
            // Normalize plurals
            if (unit.endsWith('s')) unit = unit.slice(0, -1);
            
            // Map known units
            if (unit.includes('bonus')) return { time_value: parseInt(match[1]), time_unit: 'Bonus Action' };
            if (unit.includes('reaction')) return { time_value: parseInt(match[1]), time_unit: 'Reaction' };
            
            const validUnits = ['Action', 'Minute', 'Hour', 'Day', 'Round', 'Year'];
            const capitalized = unit.charAt(0).toUpperCase() + unit.slice(1);
            
            if (validUnits.includes(capitalized)) {
                 return { time_value: parseInt(match[1]), time_unit: capitalized };
            }
        }
        return { time_value: 1, time_unit: 'Action' }; // Default fallback
    }

    function parseRangeConfig(raw?: string) {
        if (!raw) return null;
        const normalized = raw.toLowerCase().trim();
        
        let value = 0;
        let unit = 'Feet';
        let shape: 'cone' | 'cube' | 'cylinder' | 'line' | 'sphere' | null = null;

        if (normalized === 'touch') {
            unit = 'Touch';
        } else if (normalized.startsWith('self')) {
            unit = 'Self';
            // Try to extract shape from "Self (15-foot cone)"
            const shapeMatch = normalized.match(/\(([\d]+)-foot[- ]([a-z]+)\)/);
            if (shapeMatch) {
                value = parseInt(shapeMatch[1]);
                const shapeStr = shapeMatch[2]; // cone, sphere, etc
                if (['cone', 'cube', 'cylinder', 'line', 'sphere'].includes(shapeStr)) {
                    shape = shapeStr as any;
                }
            }
        } else {
            // "60 feet", "1 mile"
            const match = normalized.match(/^(\d+)\s+(feet|mile|miles)/);
            if (match) {
                value = parseInt(match[1]);
                unit = match[2].startsWith('mile') ? 'Mile' : 'Feet';
            }
        }

        return {
            range_value: value,
            range_unit: unit,
            shape: shape
        };
    }

    function parseMechanicsConfig(raw?: string) {
        if (!raw) return null;
        // "V, S, M (a drop of blood)"
        return {
            verbal: raw.includes('V'),
            somatic: raw.includes('S'),
            material: raw.includes('M'),
            materials_description: raw.match(/M\s*\(([^)]+)\)/)?.[1] || null
        };
    }

    // --- 2. Spells (Molecules) ---
    console.log(`\n📚 Seeding ${SPELLS.length} spells...`);
    for (const rawData of SPELLS) {
        const data = rawData as unknown as SeedSpell;
        
        // Normalize School Enum
        const schoolStr = data.school ? (data.school.charAt(0).toUpperCase() + data.school.toLowerCase().slice(1)) : 'Evocation';
        const validSchools = ['Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation'];
        const school = validSchools.includes(schoolStr) ? schoolStr : 'Evocation';

        const payload = {
            slug: data.slug,
            name: data.name,
            level: parseInt(String(data.level)),
            school: school as any, 
            description: data.description,
            lore: data.lore || undefined,
            casting_config: parseCastingConfig(data.casting_time),
            range_config: parseRangeConfig(data.range),
            mechanics_config: parseMechanicsConfig(data.components),
            publishedAt: new Date()
        };

        const existing = await strapi.documents('api::spell.spell').findFirst({ filters: { slug: data.slug } });
        if (existing) {
            // Partial Update
            await strapi.documents('api::spell.spell').update({ 
                documentId: existing.documentId, 
                data: {
                    description: payload.description,
                    lore: payload.lore,
                    casting_config: payload.casting_config,
                    range_config: payload.range_config,
                    mechanics_config: payload.mechanics_config
                }
            });
        } else {
            await strapi.documents('api::spell.spell').create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Spells Done.');

    // --- 3. Items (Molecules) ---
    console.log(`\n📚 Seeding ${ITEMS.length} items...`);
    for (const rawData of ITEMS) {
        const data = rawData as unknown as SeedItem;
        
        const validRarities = ['common', 'uncommon', 'rare', 'very_rare', 'legendary', 'artifact'];
        let rarity = (data.rarity || 'common').toLowerCase().replace(/ /g, '_');
        if (!validRarities.includes(rarity)) {
             console.warn(`⚠️ Invalid rarity '${rarity}' for ${data.slug}, defaulting to 'common'`);
             rarity = 'common';
        }

        const payload = {
            slug: data.slug,
            name: data.name,
            rarity: rarity as any, 
            type: 'wondrous_item' as const, // Strict enum match
            description: data.description,
            lore: data.lore || undefined,
            publishedAt: new Date()
        };
        
         const existing = await strapi.documents('api::item.item').findFirst({ filters: { slug: data.slug } });
        if (existing) {
            // Partial Update
            await strapi.documents('api::item.item').update({ 
                documentId: existing.documentId, 
                data: {
                    description: payload.description,
                    lore: payload.lore
                }
            });
        } else {
            await strapi.documents('api::item.item').create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Items Done.');

    // --- 4. Classes (Relations & Components) ---
    console.log(`\n📚 Seeding ${CLASSES.length} classes...`);
    for (const rawData of CLASSES) {
        const data = rawData as unknown as SeedClass;
        
        const featureSlugsToFind = new Set<string>();
        
        // 1. Gather all mentioned feature slugs to bulk load
        if (Array.isArray(data.features)) {
            data.features.forEach(f => featureSlugsToFind.add(f));
        }
        if (Array.isArray(data.progression)) {
             data.progression.forEach(row => {
                 if (Array.isArray(row.features)) {
                      row.features.forEach(fName => {
                           const s = fName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
                           featureSlugsToFind.add(s);
                      });
                 }
             });
        }

        // 2. Lookup Features (Get ID, Name, Description)
        const featureMap = new Map<string, { documentId: string; name: string; description: string }>();
        if (featureSlugsToFind.size > 0) {
            const foundFeatures = await strapi.documents('api::feature.feature').findMany({
                filters: { slug: { $in: Array.from(featureSlugsToFind) } },
                fields: ['documentId', 'name', 'description', 'slug']
            });
            foundFeatures.forEach((f: any) => {
                featureMap.set(f.slug, { 
                    documentId: f.documentId, 
                    name: f.name, 
                    description: typeof f.description === 'string' ? f.description : '' 
                });
            });
        }

        // 3. Construct 'features' Component Array (Embedding data)
        // Schema: features is Component<'game.feature', true>
        const featuresComponent: GameFeatureComponent[] = [];
        if (Array.isArray(data.features)) {
             data.features.forEach(slug => {
                 const f = featureMap.get(slug);
                 if (f) {
                     featuresComponent.push({
                         name: f.name,
                         description: f.description,
                         source: 'class'
                     });
                 }
             });
        }

        // 4. Construct 'progression' Component Array (Linking via Relations)
        // Schema: progression is Component<'game.class-progression', true>
        //     attributes: level, features (Relation to api::feature.feature)
        const progressionComponent: GameClassProgressionComponent[] = [];
        if (Array.isArray(data.progression)) {
             data.progression.forEach(row => {
                 const rowFeatures: string[] = [];
                 if (Array.isArray(row.features)) {
                     row.features.forEach(fName => {
                         const s = fName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
                         const f = featureMap.get(s);
                         if (f) rowFeatures.push(f.documentId);
                     });
                 }
                 progressionComponent.push({
                     level: row.level,
                     features: rowFeatures
                 });
             });
        }

        const payload = {
            slug: data.slug,
            name: data.name,
            hit_die: String(data.hit_die),
            lore: data.lore || undefined,
            features: featuresComponent, 
            progression: progressionComponent,
            publishedAt: new Date()
        };

        const existing = await strapi.documents('api::class.class').findFirst({ filters: { slug: data.slug } });
        if (existing) {
            await strapi.documents('api::class.class').update({ 
                documentId: existing.documentId, 
                data: {
                    lore: payload.lore,
                    features: payload.features,
                    progression: payload.progression
                }
            });
        } else {
            await strapi.documents('api::class.class').create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Classes Done.');

    // --- 5. Traits (Atoms) ---
    const { TRAITS } = await import('../../genesis/seed-data/traits');
    console.log(`\n📚 Seeding ${TRAITS.length} traits...`);
    for (const rawData of TRAITS) {
        const data = rawData as any; // Strict typing if available, else any
        const payload = {
             slug: data.slug,
             name: data.name,
             description: data.description,
             publishedAt: new Date()
        };
        const existing = await strapi.documents('api::trait.trait').findFirst({ filters: { slug: data.slug } });
        if (existing) {
             await strapi.documents('api::trait.trait').update({
                 documentId: existing.documentId,
                 data: { description: payload.description }
             });
        } else {
             await strapi.documents('api::trait.trait').create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Traits Done.');

    // --- 6. Races (Molecules) ---
    const { RACES } = await import('../../genesis/seed-data/races');
    console.log(`\n📚 Seeding ${RACES.length} races...`);
    for (const rawData of RACES) {
        const data = rawData as any;
        const payload = {
             slug: data.slug,
             name: data.name,
             description: data.description,
             size: data.size, // Enum match?
             speed: data.speed, // JSON
             publishedAt: new Date()
        };
        // Link Traits
        if (Array.isArray(data.traits)) {
            const traitSlugs = data.traits.map((t: string) => t.toLowerCase().replace(/ /g, '-'));
            const traits = await strapi.documents('api::trait.trait').findMany({ filters: { slug: { $in: traitSlugs } } });
            (payload as any).traits = traits.map((t: any) => t.documentId);
        }

        const existing = await strapi.documents('api::race.race').findFirst({ filters: { slug: data.slug } });
        if (existing) {
             await strapi.documents('api::race.race').update({
                 documentId: existing.documentId,
                 data: payload
             });
        } else {
             await strapi.documents('api::race.race').create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Races Done.');

    // --- 7. Monsters (Blueprints -> api::entity.entity) ---
    const { MONSTERS } = await import('../../genesis/seed-data/monsters');
    console.log(`\n📚 Seeding ${MONSTERS.length} monsters...`);
    for (const rawData of MONSTERS) {
        const data = rawData as any;
        
        // Map stats to Component
        const stats = {
            str: data.stats.str,
            dex: data.stats.dex,
            con: data.stats.con,
            int: data.stats.int,
            wis: data.stats.wis,
            cha: data.stats.cha,
            hp: data.hp,
            ac: data.ac,
            cr: data.challenge_rating,
            xp: data.xp,
            hit_dice: data.hit_dice
        };

        // Map Actions to Component logic if needed, or just store as JSON/Components
        // Schema for api::entity.entity likely has 'actions' as a Dynamic Zone or Repeater?
        // Checking CompilationOrchestrator, actions is populated.
        // Assuming simple seeding for now without complex action mapping if schema is complex.
        // We will seed the Entity with stats and basic info.
        
        const payload = {
            slug: data.slug,
            name: data.name,
            description: `A level ${data.level} ${data.type}.`,
            stats: stats,
            // We map 'type' to a field if it exists, or just description
            publishedAt: new Date()
        };

        const existing = await strapi.documents('api::entity.entity').findFirst({ filters: { slug: data.slug } });
        if (existing) {
             await strapi.documents('api::entity.entity').update({
                 documentId: existing.documentId,
                 data: { stats: payload.stats }
             });
        } else {
             await strapi.documents('api::entity.entity').create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Monsters Done.');
    
    console.log(`\n✨ \x1b[32mCanonical Seeding Complete!\x1b[0m\n`);

  } catch (error: any) {
    console.error('FULL ERROR:', JSON.stringify(error, null, 2));
    if (error.details) {
        console.error('ERROR DETAILS:', JSON.stringify(error.details, null, 2));
    }
    process.exit(1);
  } finally {
    try { await strapi.destroy(); } catch(e) {}
    process.exit(0);
  }
}

main();
