export {};
import dotenv from 'dotenv';
import path from 'path';
import { loadTags } from './tag-loader';
import { loadAtoms } from './atoms-loader';
import fs from 'fs';

// Component Interfaces (Matching types/generated/components.d.ts)
interface GameFeatureComponent {
    name: string;
    description?: string;
    source?: 'class'; // Enum subset
    usage_max?: number;
    usage_per?: 'short_rest' | 'long_rest' | 'day' | 'dawn' | 'dusk' | 'other';
}

interface GameClassProgressionComponent {
    level: number;
    pb?: number;
    features?: string[]; // documentIds for Relation
}

// 1. Load Environment Variables
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

// 2. Define Strict Seed Data Interfaces
interface SeedSpell {
    slug: string;
    name: string;
    level: number | string;
    school: string;
    description: string;
    lore?: string;
    casting_time?: string;
    range?: string;
    components?: string;
    duration?: string;
}

interface SeedItem {
    slug: string;
    name: string;
    rarity?: string;
    type?: string;
    description: string;
    lore?: string;
    requires_attunement?: boolean;
}

interface SeedClass {
    slug: string;
    name: string;
    hit_die: number | string;
    lore?: string;
    features?: string[]; // Array of slugs
    progression?: Array<{
        level: number;
        pb: number;
        features: string[];
    }>;
}

async function main() {
  console.log('✨  \x1b[1m\x1b[32mStarting Canonical Seeder (Strict Relational Ingest)...\x1b[0m\n');

  const backendRoot = path.resolve(__dirname, '../../..');
  process.chdir(backendRoot);

  const { createStrapi } = await import('@strapi/strapi');
  const strapi: any = await createStrapi({
    appDir: backendRoot,
    distDir: 'dist',
  }).load();

  try {
    // --- Load Seed Data ---
    console.log('📦 Loading TS Seed Data...');
    // We expect these to be generated by compile-seeds.ts
    const { SPELLS } = await import('../../genesis/seed-data/spells');
    const { ITEMS } = await import('../../genesis/seed-data/items');
    const { CLASSES } = await import('../../genesis/seed-data/classes');
    
    // --- 0. Atoms: Layers (Tags, Damage, Schools, Features, Terrains, Languages, Prompts) ---
    // Seed these first as they are dependencies.
    
    // Tags (The Foundation)
    await loadTags(strapi);
    
    // Atoms Loader (The Main Reference Data)
    await loadAtoms(strapi);

    // --- Helper Parsers ---

    function parseCastingConfig(raw?: string) {
        if (!raw) return null;
        const normalized = raw.toLowerCase().trim();
        // match "1 action", "10 minutes", "1 reaction"
        const match = normalized.match(/^(\d+)\s+(.+)$/);
        if (match) {
            let unit = match[2];
            if (unit.endsWith('s')) unit = unit.slice(0, -1);
            if (unit.includes('bonus')) return { time_value: parseInt(match[1]), time_unit: 'Bonus Action' };
            if (unit.includes('reaction')) return { time_value: parseInt(match[1]), time_unit: 'Reaction' };
            const validUnits = ['Action', 'Minute', 'Hour', 'Day', 'Round', 'Year'];
            const capitalized = unit.charAt(0).toUpperCase() + unit.slice(1);
            if (validUnits.includes(capitalized)) return { time_value: parseInt(match[1]), time_unit: capitalized };
        }
        return { time_value: 1, time_unit: 'Action' }; 
    }

    function parseRangeConfig(raw?: string) {
        if (!raw) return null;
        const normalized = raw.toLowerCase().trim();
        let value = 0;
        let unit = 'Feet';
        let shape: 'cone' | 'cube' | 'cylinder' | 'line' | 'sphere' | null = null;
        if (normalized === 'touch') { unit = 'Touch'; } 
        else if (normalized.startsWith('self')) {
            unit = 'Self';
            const shapeMatch = normalized.match(/\(([\d]+)-foot[- ]([a-z]+)\)/);
            if (shapeMatch) {
                value = parseInt(shapeMatch[1]);
                const shapeStr = shapeMatch[2];
                if (['cone', 'cube', 'cylinder', 'line', 'sphere'].includes(shapeStr)) shape = shapeStr as any;
            }
        } else {
            const match = normalized.match(/^(\d+)\s+(feet|mile|miles)/);
            if (match) {
                value = parseInt(match[1]);
                unit = match[2].startsWith('mile') ? 'Mile' : 'Feet';
            }
        }
        return { range_value: value, range_unit: unit, shape: shape };
    }

    function parseMechanicsConfig(raw?: string) {
        if (!raw) return null;
        return {
            verbal: raw.includes('V'),
            somatic: raw.includes('S'),
            material: raw.includes('M'),
            materials_description: raw.match(/M\s*\(([^)]+)\)/)?.[1] || null
        };
    }

    // --- 2. Spells (Molecules) ---
    console.log(`\n📚 Seeding ${SPELLS.length} spells...`);
    for (const rawData of SPELLS) {
        const data = rawData as unknown as SeedSpell;
        const schoolStr = data.school ? (data.school.charAt(0).toUpperCase() + data.school.toLowerCase().slice(1)) : 'Evocation';
        const validSchools = ['Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation'];
        const school = validSchools.includes(schoolStr) ? schoolStr : 'Evocation';

        const payload = {
            slug: data.slug,
            name: data.name,
            level: parseInt(String(data.level)),
            school: school as any, 
            description: data.description,
            lore: data.lore || undefined,
            casting_config: parseCastingConfig(data.casting_time),
            range_config: parseRangeConfig(data.range),
            mechanics_config: parseMechanicsConfig(data.components),
            publishedAt: new Date()
        };

        const existing = await strapi.documents('api::spell.spell' as any).findFirst({ filters: { slug: data.slug } });
        if (existing) {
            await strapi.documents('api::spell.spell' as any).update({ 
                documentId: existing.documentId, 
                data: {
                    description: payload.description,
                    lore: payload.lore,
                    casting_config: payload.casting_config,
                    range_config: payload.range_config,
                    mechanics_config: payload.mechanics_config
                }
            });
        } else {
            await strapi.documents('api::spell.spell' as any).create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Spells Done.');

    // --- 3. Items (Molecules) ---
    console.log(`\n📚 Seeding ${ITEMS.length} items...`);
    for (const rawData of ITEMS) {
        const data = rawData as unknown as SeedItem;
        const validRarities = ['common', 'uncommon', 'rare', 'very_rare', 'legendary', 'artifact'];
        let rarity = (data.rarity || 'common').toLowerCase().replace(/ /g, '_');
        if (!validRarities.includes(rarity)) rarity = 'common';

        const payload = {
            slug: data.slug,
            name: data.name,
            rarity: rarity as any, 
            type: 'wondrous_item' as const, 
            description: data.description,
            lore: data.lore || undefined,
            publishedAt: new Date()
        };
        
         const existing = await strapi.documents('api::item.item' as any).findFirst({ filters: { slug: data.slug } });
        if (existing) {
            await strapi.documents('api::item.item' as any).update({ 
                documentId: existing.documentId, 
                data: { description: payload.description, lore: payload.lore }
            });
        } else {
            await strapi.documents('api::item.item' as any).create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Items Done.');

    // --- 4. Classes (Relations & Components) ---
    console.log(`\n📚 Seeding ${CLASSES.length} classes...`);
    for (const rawData of CLASSES) {
        const data = rawData as unknown as SeedClass;
        
        const featureSlugsToFind = new Set<string>();
        if (Array.isArray(data.features)) data.features.forEach(f => featureSlugsToFind.add(f));
        if (Array.isArray(data.progression)) {
             data.progression.forEach(row => {
                 if (Array.isArray(row.features)) {
                      row.features.forEach(fName => {
                           const s = fName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
                           featureSlugsToFind.add(s);
                      });
                 }
             });
        }

        const featureMap = new Map<string, { documentId: string; name: string; description: string }>();
        if (featureSlugsToFind.size > 0) {
            const foundFeatures = await strapi.documents('api::feature.feature' as any).findMany({
                filters: { slug: { $in: Array.from(featureSlugsToFind) } },
                fields: ['documentId', 'name', 'description', 'slug']
            });
            foundFeatures.forEach((f: any) => {
                featureMap.set(f.slug, { 
                    documentId: f.documentId, 
                    name: f.name, 
                    description: typeof f.description === 'string' ? f.description : '' 
                });
            });
        }

        const featuresComponent: GameFeatureComponent[] = [];
        if (Array.isArray(data.features)) {
             data.features.forEach(slug => {
                 const f = featureMap.get(slug);
                 if (f) featuresComponent.push({ name: f.name, description: f.description, source: 'class' });
             });
        }

        const progressionComponent: GameClassProgressionComponent[] = [];
        if (Array.isArray(data.progression)) {
             data.progression.forEach(row => {
                 const rowFeatures: string[] = [];
                 if (Array.isArray(row.features)) {
                     row.features.forEach(fName => {
                         const s = fName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
                         const f = featureMap.get(s);
                         if (f) rowFeatures.push(f.documentId);
                     });
                 }
                 progressionComponent.push({ level: row.level, features: rowFeatures });
             });
        }

        const payload = {
            slug: data.slug,
            name: data.name,
            hit_die: String(data.hit_die),
            lore: data.lore || undefined,
            features: featuresComponent, 
            progression: progressionComponent,
            publishedAt: new Date()
        };

        const existing = await strapi.documents('api::class.class' as any).findFirst({ filters: { slug: data.slug } });
        if (existing) {
            await strapi.documents('api::class.class' as any).update({ 
                documentId: existing.documentId, 
                data: { lore: payload.lore, features: payload.features, progression: payload.progression }
            });
        } else {
            await strapi.documents('api::class.class' as any).create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Classes Done.');

    // --- 5. Traits (Atoms) ---
    const { TRAITS } = await import('../../genesis/seed-data/traits');
    console.log(`\n📚 Seeding ${TRAITS.length} traits...`);
    for (const rawData of TRAITS) {
        const data = rawData as any;
        const payload = {
             slug: data.slug,
             name: data.name,
             description: data.description,
             publishedAt: new Date()
        };
        const existing = await strapi.documents('api::trait.trait' as any).findFirst({ filters: { slug: data.slug } });
        if (existing) {
             await strapi.documents('api::trait.trait' as any).update({
                 documentId: existing.documentId,
                 data: { description: payload.description }
             });
        } else {
             await strapi.documents('api::trait.trait' as any).create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Traits Done.');

    // --- 6. Races (Molecules) ---
    const { RACES } = await import('../../genesis/seed-data/races');
    console.log(`\n📚 Seeding ${RACES.length} races...`);
    for (const rawData of RACES) {
        const data = rawData as any;
        const payload = {
             slug: data.slug,
             name: data.name,
             description: data.description,
             size: data.size, 
             speed: data.speed, 
             publishedAt: new Date()
        };
        if (Array.isArray(data.traits)) {
            const traitSlugs = data.traits.map((t: string) => t.toLowerCase().replace(/ /g, '-'));
            const traits = await strapi.documents('api::trait.trait' as any).findMany({ filters: { slug: { $in: traitSlugs } } });
            (payload as any).traits = traits.map((t: any) => t.documentId);
        }

        const existing = await strapi.documents('api::race.race' as any).findFirst({ filters: { slug: data.slug } });
        if (existing) {
             await strapi.documents('api::race.race' as any).update({ documentId: existing.documentId, data: payload });
        } else {
             await strapi.documents('api::race.race' as any).create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Races Done.');
    
    // --- 6.5 Queue Configuration (Single Type) ---
    console.log('\n⚙️  Seeding Queue Config...');
    try {
        const queueConfigPath = path.join(backendRoot, 'data/library/atoms/queue-config.json');
        if (fs.existsSync(queueConfigPath)) {
            const queueData = JSON.parse(fs.readFileSync(queueConfigPath, 'utf-8'));
            const qc = await strapi.documents('api::queue-configuration.queue-configuration' as any).findFirst();
            const qcPayload = {
                globalEnabled: true,
                queues: queueData, // Component array matches structure
                publishedAt: new Date()
            };
            
            if (qc) {
                await strapi.documents('api::queue-configuration.queue-configuration' as any).update({
                    documentId: qc.documentId,
                    data: qcPayload
                });
            } else {
                await strapi.documents('api::queue-configuration.queue-configuration' as any).create({
                   data: qcPayload 
                });
            }
            console.log('✅ Queue Config Synced.');
        } else {
            console.warn('⚠️ queue-config.json not found.');
        }
    } catch(err) {
        console.error('❌ Failed to seed Queue Config:', err);
    }

    // --- 7. Rule Set (Single Type) ---
    console.log('\n📜 Seeding Rule Set...');
    const xpTable = [0, 300, 900, 2700, 6500, 14000, 23000, 34000, 48000, 64000, 85000, 100000, 120000, 140000, 165000, 195000, 225000, 265000, 305000, 355000];
    const proficiencyTable = [2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6];
    
    const ruleSet = await strapi.documents('api::rule-set.rule-set' as any).findFirst();
    if (!ruleSet) {
        await strapi.documents('api::rule-set.rule-set' as any).create({
            data: {
                xp_table: xpTable,
                proficiency_table: proficiencyTable,
                publishedAt: new Date()
            }
        });
        console.log('✅ Rule Set Created.');
    } else {
        console.log('ℹ️ Rule Set already exists.');
    }

    // --- 8. Monsters (Blueprints -> api::entity.entity) ---
    const { MONSTERS } = await import('../../genesis/seed-data/monsters');
    console.log(`\n📚 Seeding ${MONSTERS.length} monsters...`);
    for (const rawData of MONSTERS) {
        const data = rawData as any;
        const stats = {
            str: data.stats.str, dex: data.stats.dex, con: data.stats.con,
            int: data.stats.int, wis: data.stats.wis, cha: data.stats.cha,
            hp: data.hp, ac: data.ac, cr: data.challenge_rating,
            xp: data.xp, hit_dice: data.hit_dice
        };

        const payload = {
            slug: data.slug,
            name: data.name,
            description: `A level ${data.level} ${data.type}.`,
            stats: stats,
            publishedAt: new Date()
        };

        const existing = await strapi.documents('api::entity.entity' as any).findFirst({ filters: { slug: data.slug } });
        if (existing) {
             await strapi.documents('api::entity.entity' as any).update({
                 documentId: existing.documentId,
                 data: { stats: payload.stats }
             });
        } else {
             await strapi.documents('api::entity.entity' as any).create({ data: payload });
        }
        process.stdout.write('.');
    }
    console.log('\n✅ Monsters Done.');
    
    console.log(`\n✨ \x1b[32mCanonical Seeding Complete!\x1b[0m\n`);

  } catch (error: any) {
    console.error('FULL ERROR:', JSON.stringify(error, null, 2));
    if (error.details) {
        console.error('ERROR DETAILS:', JSON.stringify(error.details, null, 2));
    }
    process.exit(1);
  } finally {
    try { await strapi.destroy(); } catch(_e) { /* ignore */ }
    process.exit(0);
  }
}

main();
