
import fs from 'fs';
import path from 'path';
import { glob } from 'glob';
import dotenv from 'dotenv';

dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

const RA_ROOT = path.resolve(__dirname, '../../../data/library');
const AUDIT_ROOT = path.join(RA_ROOT, 'audit');
// TARGET: src/genesis/seed-data
const TARGET_ROOT = path.resolve(__dirname, '../../genesis/seed-data');

// Ensure target exists
if (!fs.existsSync(TARGET_ROOT)) {
    fs.mkdirSync(TARGET_ROOT, { recursive: true });
}

async function loadAndMerge(type: 'features' | 'classes' | 'spells' | 'items' | 'monsters' | 'races' | 'traits', subDir: string) {
    const rawFiles = await glob(`${subDir}/*.json`, { cwd: RA_ROOT });
    const mergedList: any[] = [];

    console.log(`\n📚 Processing ${type} (${rawFiles.length} files)...`);

    for (const file of rawFiles) {
        const rawPath = path.join(RA_ROOT, file);
        const rawContent = JSON.parse(fs.readFileSync(rawPath, 'utf-8'));
        // Normalize to array (some parser outputs are [Object], some are Object)
        const rawItems = Array.isArray(rawContent) ? rawContent : [rawContent];

        for (const rawItem of rawItems) {
            let merged = { ...rawItem };

            // Find Audit
            // Audit naming convention: {slug}.audit.json
            // We assume 1 file = 1 entity roughly, or the audit matches the filename.
            const basename = path.basename(file, '.json');
            const auditPath = path.join(AUDIT_ROOT, `${basename}.audit.json`);

            if (fs.existsSync(auditPath)) {
                try {
                    const audit = JSON.parse(fs.readFileSync(auditPath, 'utf-8'));
                    
                    // 1. Text Polish
                    if (audit.description_polished) merged.description = audit.description_polished;
                    if (audit.lore_snippet) merged.lore = audit.lore_snippet;

                    // 2. Mechanics Fixes (Naive spread)
                    if (audit.mechanics_fix && typeof audit.mechanics_fix === 'object') {
                        merged = { ...merged, ...audit.mechanics_fix };
                    }
                } catch (e) {
                    console.warn(`⚠️  Audit load failed for ${basename}:`, e);
                }
            }
            
            mergedList.push(merged);
        }
        process.stdout.write('.');
    }
    return mergedList;
}

function generateTSFile(filename: string, variableName: string, data: any[]) {
    const content = `// ⚠️ AUTO-GENERATED BY COMPILE-SEEDS. DO NOT EDIT.
// Generated at: ${new Date().toISOString()}

export const ${variableName} = ${JSON.stringify(data, null, 2)} as const;
`;
    fs.writeFileSync(path.join(TARGET_ROOT, filename), content);
    console.log(`\n✅ Generated ${filename} (${data.length} entries)`);
}

async function main() {
    console.log('🧬 Starting TS Seed Compiler...');

    // 1. Features
    const features = await loadAndMerge('features', 'atoms/features');
    generateTSFile('features.ts', 'FEATURES', features);

    // 2. Spells
    const spells = await loadAndMerge('spells', 'molecules/spells');
    generateTSFile('spells.ts', 'SPELLS', spells);

    // 3. Items
    const items = await loadAndMerge('items', 'molecules/items');
    generateTSFile('items.ts', 'ITEMS', items);

    // 4. Classes
    const classes = await loadAndMerge('classes', 'molecules/classes');
    generateTSFile('classes.ts', 'CLASSES', classes);

    // 5. Monsters (Blueprints)
    // Blueprints are stored in batches: monsters-batch-*.json
    const monsters = await loadAndMerge('monsters', 'blueprints');
    generateTSFile('monsters.ts', 'MONSTERS', monsters);

    // 6. Traits (Atoms)
    // Traits are in atoms/traits.json. loadAndMerge globs *.json so it will pick it up if we point to atoms/
    // BUT atoms/ has other stuff. We should filter?
    // Actually loadAndMerge takes a SUBDIR. If we pass 'atoms', it gets all atoms.
    // Let's rely on the glob pattern being specific if possible, OR just parse the specific file manually for traits.
    // For now, let's try to glob specific file or just load explicitly.
    // Re-using loadAndMerge for simplicity but creating a temp subdir approach or just manual load.
    // Actually, let's just use loadAndMerge('traits', 'atoms') but we need to filter inside?
    // No, loadAndMerge iterates ALL json in the dir. 
    // Let's just manually load traits.json for precision.
    
    console.log('\n📚 Processing traits...');
    const traitsPath = path.join(RA_ROOT, 'atoms/traits.json');
    if (fs.existsSync(traitsPath)) {
        const rawTraits = JSON.parse(fs.readFileSync(traitsPath, 'utf-8'));
        generateTSFile('traits.ts', 'TRAITS', Array.isArray(rawTraits) ? rawTraits : [rawTraits]);
    } else {
        console.warn('⚠️ traits.json not found');
        generateTSFile('traits.ts', 'TRAITS', []);
    }

    // 7. Races (Molecules)
    const races = await loadAndMerge('races', 'molecules/races');
    generateTSFile('races.ts', 'RACES', races);

    console.log('\n🎉 TS Seed Generation Complete!');
}

main()
.catch(console.error);
