import dotenv from 'dotenv';
dotenv.config();

import { ChatGoogleGenerativeAI } from '@langchain/google-genai';
import { z } from 'zod';
import fs from 'fs';
import path from 'path';

// Define the blueprint schema we want from the LLM
const GenerativeBlueprintSchema = z.object({
  name: z.string().describe('e.g. Humanoid (Huge)'),
  slug: z.string().describe('e.g. humanoid-huge'),
  category: z.string().describe('e.g. Creature, Object, Terrain'),
  grid: z
    .array(z.string())
    .describe('An array of strings, where each string is exactly 1 row of characters representing the entire width. e.g. "   OOOO   ".'),
  zones: z.array(z.string()).describe('An array of string slugs for the zones.'),
  mapping: z.array(z.object({ symbol: z.string().describe('1-char symbol used in grid'), zoneSlug: z.string().describe('Valid zone slug') })).describe('Maps symbols to zone slugs.'),
  anchors: z.array(z.object({ zoneSlug: z.string().describe('Valid zone slug'), coords: z.object({ x: z.number(), y: z.number() }).describe('X and Y coordinates') })).describe('Zone anchors.'),
});

type GenerativeBlueprint = z.infer<typeof GenerativeBlueprintSchema>;

const model = new ChatGoogleGenerativeAI({
  model: 'gemini-3-pro-preview', // Or whatever strict internal name maps to the best reasoning model
  temperature: 0.1, // Low temp for accurate mathematical structure
});

// The model instance with structured output
const structuredModel = model.withStructuredOutput(GenerativeBlueprintSchema);

// Constants mapped to D&D Sizes
const SIZE_GRID_MAP: Record<string, number> = {
  Tiny: 32,
  Small: 32,
  Medium: 32,
  Large: 64, // 2x2 squares
  Huge: 96, // 3x3 squares
  Gargantuan: 128, // 4x4+ squares
};

const BASE_ARCHETYPES = [
  {
    archetype: 'Humanoid',
    category: 'Creature',
    zones: ['head', 'core', 'legs', 'hand-l', 'hand-r'],
  },
  {
    archetype: 'Beast Quadruped',
    category: 'Creature',
    zones: ['head', 'core', 'legs', 'tail', 'accessory'],
  },
  // Add more base archetypes here...
];

const TARGET_SIZES = ['Tiny', 'Small', 'Medium', 'Large', 'Huge', 'Gargantuan'];

// Paths to your template files
const DEST_DIR = path.join(process.cwd(), 'src', 'genesis', 'blueprints', 'blueprint');

async function generateBlueprint(
  archetypeData: (typeof BASE_ARCHETYPES)[0],
  size: string
): Promise<GenerativeBlueprint | null> {
  const finalResolution = SIZE_GRID_MAP[size];
  const resolution = 32; // Everything is generated by LLM at 32x32 to save tokens and guarantee perfect compile

  // Specific sizing constraints based on D&D rules
  let sizingInstruction = `
Your canvas is exactly ${resolution} pixels wide and ${resolution} pixels high.
You MUST output an array of strings (where array.length === ${resolution} rows), and EACH string must be exactly ${resolution} characters long.
Fill empty space with a single space character: " ". 
`;

  if (size === 'Tiny') {
    sizingInstruction += `
For a Tiny creature, the anatomy should only occupy roughly an 8x8 to 16x16 pixel area perfectly centered inside the 32x32 grid.
`;
  } else if (size === 'Small') {
    sizingInstruction += `
For a Small creature, the anatomy should occupy roughly a 20x20 pixel area perfectly centered inside the 32x32 grid.
`;
  } else {
    sizingInstruction += `
For a ${size} creature, it should fill a significant portion of its ${resolution}x${resolution} grid. Center it perfectly using the entire 32x32 space. We will mathematically scale this up to ${finalResolution}x${finalResolution} later.
`;
  }

  const prompt = `
You are formulating a mathematical, semantic Blueprint for a procedurally generated 2D Sprite Engine.
Your task is to plot the anatomical zones of a "${archetypeData.archetype} (${size})" onto a 2D text grid.

RULES:
1. Canvas Resolution: ${sizingInstruction}
2. The entity is a ${archetypeData.category}.
3. The valid physical zones to plot are: ${archetypeData.zones.join(', ')}.
4. Choose exactly one unique single-character symbol (like 'O', '#', 'L', '<', '>') for each zone.
5. In the \`mapping\` object, map each of those symbols to the corresponding zone slug.
6. In the \`grid\` array of strings, physically "draw" the entity using those symbols. Make sure limbs, heads, and cores are geographically coherent (e.g., head on top, core in middle, legs at bottom, left/right hands on sides).
7. In the \`anchors\` object, calculate the exact [X, Y] (Column, Row) coordinate where the center mass of each zone is located within the ${resolution}x${resolution} space. Keep in mind string indices are 0-based.
8. The \`name\` should be "${archetypeData.archetype} (${size})".
9. The \`slug\` should be "${archetypeData.archetype.toLowerCase().replace(/\s+/g, '-')}-${size.toLowerCase()}".

Ensure the anatomy scales properly to match the massive or tiny sizes in D&D rules!
`;

  console.log(`\n🧠 Prompting Gemini 3 Pro for ${archetypeData.archetype} (${size})... Grid: ${resolution}x${resolution}`);

  try {
    const result = await structuredModel.invoke([['human', prompt]]);
    return result;
  } catch (err) {
    console.error(`❌ Failed to generate ${archetypeData.archetype} (${size})`);
    console.error(err);
    return null;
  }
}

// Hex code default definitions (Normally fetched from DB)
const ZONE_COLORS: Record<string, string> = {
  head: '#FFCCCC',
  core: '#CCFFCC',
  legs: '#CCCCFF',
  tail: '#FFFFCC',
  'hand-l': '#FFCCFF',
  'hand-r': '#CCFFFF',
  accessory: '#DDDDDD'
};

function writeBlueprintToFile(blueprint: GenerativeBlueprint, finalGridSize: number) {
  const filePathTs = path.join(DEST_DIR, `${blueprint.slug}.ts`);
  const filePathPng = path.join(process.cwd(), 'src/genesis/sprites/blueprints', `${blueprint.slug}.png`);

  // Map the array objects back to records for the blueprint file
  const mappingRecord: Record<string, string> = {};
  for (const m of blueprint.mapping) {
    mappingRecord[m.symbol] = m.zoneSlug;
  }

  const anchorRecord: Record<string, [number, number]> = {};
  for (const a of blueprint.anchors) {
    anchorRecord[a.zoneSlug] = [a.coords.x ?? 0, a.coords.y ?? 0];
  }

  const fileContent = `import { defineBlueprint } from '@/features/genesis-core/blueprints';

export default defineBlueprint({
  name: '${blueprint.name}',
  slug: '${blueprint.slug}',
  category: '${blueprint.category}',
  gridUrl: '/src/genesis/sprites/blueprints/${blueprint.slug}.png',
  zones: ${JSON.stringify(blueprint.zones)},
  mapping: ${JSON.stringify(mappingRecord, null, 4)},
  anchors: ${JSON.stringify(anchorRecord, null, 4)}
});
`;

  fs.writeFileSync(filePathTs, fileContent);
  console.log(`✅ Saved ${blueprint.slug}.ts to ${filePathTs}`);
  
  // Create raw Hex Array logic
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { hexArrayToPng } = require('../../scripts/png-to-hex.js');
  
  const hexArray: string[] = [];
  for (const row of blueprint.grid) {
     for (const char of row) {
        if (char === ' ') {
           hexArray.push('#00000000');
        } else {
           const slug = mappingRecord[char];
           hexArray.push(ZONE_COLORS[slug] || '#FF00FF'); 
        }
     }
  }

  hexArrayToPng(hexArray, finalGridSize, filePathPng)
    .then(() => console.log(`🖼️ Saved Blueprint Image to ${filePathPng}`))
    .catch((e: Error) => console.error(`❌ Failed to save PNG: ${e.message}`));
}

async function run() {
  console.log('--- 🚀 Daicer Blueprint Generative Engine ---');

  for (const archetype of BASE_ARCHETYPES) {
    for (const size of TARGET_SIZES) {
      if (!process.env.GOOGLE_API_KEY) {
        console.error('❌ GOOGLE_API_KEY is not set. Terminating.');
        process.exit(1);
      }

      const bp = await generateBlueprint(archetype, size);
      if (bp) {
        // Validate it produced the exact right grid dimensions before saving
        const expectedGridSize = 32;
        const finalGridSize = SIZE_GRID_MAP[size];
        const multiplier = Math.floor(finalGridSize / expectedGridSize);
        
        // Auto-fix lengths by padding or truncating rows to ensure perfect square mathematically
        let paddedGrid = bp.grid;
        if (paddedGrid.length > expectedGridSize) paddedGrid = paddedGrid.slice(0, expectedGridSize);
        while (paddedGrid.length < expectedGridSize) paddedGrid.push(' '.repeat(expectedGridSize));
        
        paddedGrid = paddedGrid.map(row => {
          if (row.length > expectedGridSize) return row.slice(0, expectedGridSize);
          if (row.length < expectedGridSize) return row + ' '.repeat(expectedGridSize - row.length);
          return row;
        });

        // Mathematic multiplier (Scaling the 32x32 grid up)
        const scaledGrid: string[] = [];
        for (const row of paddedGrid) {
          let scaledRow = '';
          for (const char of row) {
             scaledRow += char.repeat(multiplier);
          }
          for (let i = 0; i < multiplier; i++) {
             scaledGrid.push(scaledRow);
          }
        }
        
        bp.grid = scaledGrid;
        
        // Also scale up the mathematical anchors!
        for (const a of bp.anchors) {
          a.coords.x = Math.floor(a.coords.x * multiplier);
          a.coords.y = Math.floor(a.coords.y * multiplier);
        }

        writeBlueprintToFile(bp, finalGridSize);
      }
    }
  }

  console.log('\\n--- 🎉 Generation Complete ---');
}

run();
