// Re-export from shared to maintain backward compatibility during migration
export {
  ActionType,
  DamageSchema,
  SaveSchema,
  AttackIntentSchema,
  CastSpellIntentSchema,
  UseFeatureIntentSchema,
  DashIntentSchema,
  DisengageIntentSchema,
  DodgeIntentSchema,
  GrappleIntentSchema,
  ActionIntentSchema,
  type ActionIntent,
  MeleeAttackDefinitionSchema,
  RangedAttackDefinitionSchema,
  SpellDefinitionSchema,
  FeatureDefinitionSchema,
  ReactionTriggerSchema,
  ReactionDefinitionSchema,
  ActionDefinitionSchema,
  type ActionDefinition,
} from '@daicer/shared';
